### ISSUE TITLE
Anzeige der Such-Seite "Personen" 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#10]
![grafik](https://user-images.githubusercontent.com/40201793/48335104-0d0b6e00-e65d-11e8-9898-cbfe7bf1c3d0.png)

Bitte statt "Titel" unter dem Namen des Prof. die Professur + Fach anzeigen z.B.:
Adam, Wolfgang
Professur für Germanistik 

(ist das "für" in den Datenlieferungen noch drin)??

**Comment by dofeldsc** [comment]
Das für? Du meinst unter "Professur" steht immer "Professur für" oder "Juniorprofessur für", ja das ist in der Datenlieferung drin aber wurde von mir extra per Skript entfernt. Warum was ist damit?

**Comment by sonschul** [comment]
Wenn wir das unter dem Namen auf der Suchseiten einblenden wollen hätte man das "für" auch dahinter stehen lassen können, weil direkt dahinter das Fach erscheint. 
Ansonsten fände ich es passender, wenn es JuniorprofessOr statt Juniorprofessur unter dem Namen heißt.

**Comment by sonschul** [comment]
Nochmal zum Thema: Juniorprofessor, Stiftungsprofessor... Im KDSF sind das eigene Klassen. (vermutlich Unterklassen von Professor) Hätte man das anders mappen müssen? 
Also pro Klasse eine eigene Tabelle "Stiftungsprofessoren.xls" in die Klasse "Stiftungsprofessor" laden müssen?

**Comment by dofeldsc** [comment]
Ja, hatte ich auch mal angesprochen. Wenn ihr danach sortieren wollt oder bestimmte Filter (links) dafür braucht dann wäre das das richtige Vorgehen gewesen. So kann man es jetzt zwar anzeigen aber sehr schwer danach sortieren bzw filtern. Auch dieses "In der Property steht Juniorprofessur aber da soll Juniorprofessor stehen" ist wieder mehr Aufwand als es aussieht

**Comment by dofeldsc** [comment]
Ich habe eine Lösung gefunden.Ich kann das jetzt auch aus einer Liste machen. Ich müsste nur wissen welche Professur ihr auf welche Klasse Mappen wollt. Ich habe das Beispielhaft jetzt für den TestProf in fis.virtuos.uos.de/vivouos mit Juniorprofessur gemacht. Ich muss dann nur noch ein Skript schreiben. Das verzögert als das Laden der Daten mit den neuen IDs.

**Comment by sonschul** [comment]
Schön wäre es, wenn es in der Liste wie beim Stiftungsprofessor angezeigt wird (siehe rechts) und die Liste gefilter werden kann wie beim Juniorprofessor (siehe links): 
![grafik](https://user-images.githubusercontent.com/40201793/48409591-83cb6880-e73c-11e8-998b-7688735a7b85.png)

Welche konkreten Ausdifferenzierungen gewünscht sind, habe ich gerade nachgefragt.

**Comment by dofeldsc** [comment]
Die Klasse also hier "Stiftungsprofessur" verschwindet in der Anzeige wenn man einen Titel angibt und nach Stiftungsprofessur filtern geht nicht weil man das unter Einzelseiten-Verwaltung einstellen müsste das auch die Klassen filterbar sind. (Habe ich für Juniorprofessur gemacht) Wenn das alles noch in der Schwebe ist dann warte ich jetzt mit dem Einspielen der Daten.

**Comment by sonschul** [comment]
Bitte bis morgen warten... Frau Brüggemann hat auch noch Anmerkungen zur den Programm- und Vetretungsprofessuren, die ich morgen mit Marco noch mal besprechen muss. 
Du kannst besser auf einen neuen Datensatz warten...

**Comment by dofeldsc** [comment]
Für mich als Notiz schon mal:
Die Anzeige der Instanzen einer Klasse lässt sich zum Beispiel mit so einem Template regeln (in diesem Fall für Klasse people und alle Unterklassen)
Da sollten wir den Titel rausnehmen und dann steht aber auch immer und überall die Klasse unter der Person also nicht nur in den filterbaren Listen sondern auch in der Suche etc. 
(VIVO/webapp/src/main/webapp/templates/freemarker/body/partials/shortview/view-browse-people.ftl)

Siehe Ticket #14

**Comment by dofeldsc** [comment]
https://wiki.duraspace.org/display/VIVODOC110x/Creating+short+views+of+individuals 
Eine Anleitung aber dafür müsste ich (oder Manuel, mal schauen) uns erst mehr mit Freemarker und den Ajax/JS Skripten auseinandersetzen. Den Titel kann man rausnehmen und dann wird immer die Klasse angezeigt aber um Dinge hinzuzufügen müsste man schon wissen was man da tut

**Comment by sonschul** [comment]
Vielleicht können wir in Cornell nachfragen? Dort wird in der "Domain Expert"-Suche als Text unter dem Namen der Professoren auch der Status (z.B. Professor) und Fach bzw. bei einigen auch Fachbereich angezeigt. 

![grafik](https://user-images.githubusercontent.com/40201793/49272584-5d166d00-f472-11e8-8caa-2703364fb37f.png)

**Comment by dofeldsc** [comment]
Wie ist der Stand des Tickets? Was ist jetzt genau gewünscht? 
Ich habe gestern bei den Fachbereichen und Instituten die ShortView (Listenansicht) angepasst. Man kann durch SparQL-Queries die gewünschten Daten nachladen.

**Comment by sonschul** [comment]
Gewünscht wäre statt dem Titel "Prof. Dr." unter den Professoren als Untertitel "Professur, Denomination".
Also z.B.
Busch, Karin
"Juniorprofessur, Mitochondriale Dynamik"

**Comment by dofeldsc** [comment]
Ist eingebaut aber noch nicht für alle Unterklassen. Irgendwie sieht das komisch aus wenn es eine normale Professur ist. Dann steht da z.B. "Professur, Schlagwort Denomination"

**Comment by dofeldsc** [comment]
Funktioniert jetzt auch für alle Unterklassen von kdsf:Professor. Also 
- Vertretungsprofessoren
- Stiftungsprofessoren
- Seniorprofessoren
- OrdentlicheProfessoren
- Juniorprofessoren
- HauptberuflicheGastprofessoren
- AusserplanmaessigeProfessoren

Ihr könnt ja mal schauen ob das so passt.

**Comment by sonschul** [comment]
kannst du statt der juniorprofessoren die professoren als vorauswahl / einstiegsseite auswählen?

**Comment by dofeldsc** [comment]
mhm muss ich mir anschauen, das ist einfach alphabetisch sortiert und immer der erste Eintrag wird anfangs ausgewählt aber mal sehen

**Comment by dofeldsc** [comment]
Die Vorauszahl zu ändern lässt sich nicht einfach so machen aber ich kann die Reihenfolge ändern und dann stehen die Professoren immer an erster Stelle. Das geht über den "DisplayRank" der jeweiligen Klassen (alle kdsf-alignment).
Falls es keine Instanz der Klasse im System gibt, wird die Klasse natürlich auch nicht in der Liste angezeigt.

1 Prof
2 Juniorprof
3 Seniorprof
4 Stiftungsprof
5 Außerplanmäßigerprof
6 Vertretungsprof
7 Gastprof
8 Wissenschaftliches Personal
9 WIssenschaftliche Mitarbeiter

**Comment by dofeldsc** [comment]
Ich habe es mal hier eingebaut: https://fis.uni-osnabrueck.de/vivouos/people 
Wenn das jemand möchte, können auch die Reihenfolgen auf den anderen Seiten angepasst werden

**Comment by sonschul** [comment]
Find ich gut so! Kann auf jeden Fall übernommen werden.
