### ISSUE TITLE
Layoutanpassungen auf Startseite (Corporate Design)

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#102]
In den drei Random List Boxen müsste unten jeweils der Link zu "Alle anzeigen ..."
noch mit einem roten Pfeil ergänzt werden. 

![image](https://user-images.githubusercontent.com/40201793/90227877-92651900-de15-11ea-8822-1849ccf59015.png)

**Comment by dofeldsc** [comment]
erledigt, siehe Testsystem
