### ISSUE TITLE
Affiliationsrichtlinie im VIVO einbinden

### ISSUE THREAD

**Issue by kaschnie** [FISvirtUOS/VIVO#104]
Verlinkung zur Affiliationsrichtlinie im VIVO einbinden - wo im VIVO?

Verabschiedete Affiliationsrichtlinie irgendwo auf der Internetseiten veröffentlicht? - Nachfrage bei UB @sonschul

**Comment by dofeldsc** [comment]
![vorschlag_affiliationsrichtlinie](https://user-images.githubusercontent.com/9248706/120618300-3bd7d280-c45b-11eb-8fec-907acf9b7c4c.png)

Jetzt mal als Vorschlag auf der Seite für die Publikationen eingebunden (heißt jetzt noch "Projektveröffentlichungen"):
Oder wie habt ihr euch das vorgestellt? 

Ich bräuchte auch noch den Link zur Affiliationsrichtlinie.

**Comment by dofeldsc** [comment]
Wir haben gerade in der wöchentlichen Besprechung darüber gesprochen. 
Einen Link gibt es noch nicht.
Eine Idee wäre auch, das so wie das Impressum unten in den Footer mit aufzunehmen. Unter dem Link sollte dann das PDF herunterladbar sein.

**Comment by dofeldsc** [comment]
Die Affiliationsrichtlinie ist ab jetzt unter 
https://www.ub.uni-osnabrueck.de/publizieren_archivieren/affiliationsrichtinie.html verfügbar

**Comment by dofeldsc** [comment]
Ich habe das jetzt als Link im Footer eingebaut (siehe Foto).

**Fragen** die zu klären sind:
- Soll sich dann ein neues Fenster im Browser öffnen oder soll man direkt auf die Seite kommen?
- Ist der Text so okay? Als Titel (also Text der angezeigt wird wenn man mit der Maus über dem Link hovert) habe ich jetzt mal "Affiliationsrichtlinie UOS" genommen?!
- Was wäre die korrekte englische Übersetzung? ("Affiliation Policy" oder "Affiliate Policy")
- Soll das noch an einer anderen Stelle eingebunden werden?

![Bildschirmfoto vom 2021-07-08 10-43-16](https://user-images.githubusercontent.com/9248706/124891513-59a7d280-dfd9-11eb-8807-90a2ec6ead08.png)

**Comment by sonschul** [comment]
Find ich gut so! 

zu 1.) ich würde das grundsätzlich so handhaben, dass Seiten außerhalb von VIVO in einem neuen Fenster und nur Links zu anderen VIVO-Seite im gleichen Fenster geöffnet werden. 
zu 2.) als Mouseover-Text würde ich lieber nur "Affiliationsrichtlinie" oder sonst "Affiliationsrichtlinie der Universität Osnabrück" nehmen
zu 3.) Übersetzung Affiliation Policy wird auch von anderen Seiten genommen (Uni Göttingen) im englischsprachigen Raum aber eher "Affiliation Agreement" genannt.
4.) Nein, das reicht erstmal aus.

**Comment by dofeldsc** [comment]
Habe es gerade ins Produktivsystem übertragen

**Comment by sonschul** [comment]
Getestet und für gut befunden. ;-)
