### ISSUE TITLE
Filter / Seitenumbruch -Möglicheiten 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#11]
Auf der Personen-Suchseite wird bei "Alle" ein Umbruch nach Seiten vorgenommen. 
Ich würde das gerne entweder ganz rausnehmen oder zumindest einrücken. 

![grafik](https://user-images.githubusercontent.com/40201793/48335470-1a752800-e65e-11e8-87ab-d04eb15cff6a.png)

**Comment by dofeldsc** [comment]
Du meinst das Seite 1 2 3 einfach ein Stück nach rechts? Rausnehmen würde ich das nicht, da man auf keinen Fall eine Seite mit mehreren Hundert Objekten laden möchte.

**Comment by sonschul** [comment]
Jep, nach rechts einrücken!

**Comment by dofeldsc** [comment]
Ist erledigt (im css des Themes tenderfoot_uos)
