### ISSUE TITLE
Profilseite: Klassennamen wieder hinzufügen

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#110]
Auf den Profilseiten von Personen (zur Zeit nur als "Visitenkarte") sollen wieder die Klassennamen auftauchen.

**Comment by dofeldsc** [comment]
Welche Version findet ihr denn besser? 
Hinter dem Namen
![Bildschirmfoto vom 2021-07-08 16-44-43](https://user-images.githubusercontent.com/9248706/124942484-f5523680-e00b-11eb-88cd-8c56c1ab435e.png)

oder unter dem Namen
![Bildschirmfoto vom 2021-07-08 15-48-36](https://user-images.githubusercontent.com/9248706/124942509-fc794480-e00b-11eb-9e4e-42c9f8c217a8.png)

Ich persönlich finde die Version hinter dem Namen besser.

**Comment by sonschul** [comment]
Ich finde es auch hinter dem Namen besser, allerdings wurde heute in der Teambesprechung gesagt, dass die Empfehlung der Stadt Osnabrück mit : also Professor:in bevorzugt werden...

**Comment by kaschnie** [comment]
dito.. finde es hinter dem Namen auch besser! :)

**Comment by dofeldsc** [comment]
Alles klar, danke fürs Feedback.
Mein letzter Stand war die Empfehlung von K&M das * zu bevorzugen aber dann ändere ich das gerne wieder. Hatte das auch nur mal so nebenbei für unsere Klassennamen gemacht. Wir sollten ja immer noch das System mal durchgehen und alle Dinge richtig Gendern die wir so finden, besonders die KDSF-Ontologie da wir die hauptsächlich benutzen.

**Comment by dofeldsc** [comment]
Habe es gerade ins Produktivsystem übertragen, gerne mal schauen ob es so passt

**Comment by dofeldsc** [comment]
Jetzt passt das Template bei dem Wissensforum nicht mehr ganz, muss ich noch anpassen. (float muss da weg)

**Comment by dofeldsc** [comment]
Ist gefixt.

**Comment by dofeldsc** [comment]
Wie gerade besprochen ist das Ticket damit erledigt.
