### ISSUE TITLE
Anzeige ORCID Personen-Profil

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#111]
Die Verlinkung des ORCID-Profils soll auf dem Personen-Profil (UOS-Visitenkarte) sichtbar werden.

Ein Beispiel wie es aussehen könnte wäre sowas:
![orcid_link_profil](https://user-images.githubusercontent.com/9248706/124596908-19264880-de63-11eb-92eb-9c5e00799545.png)

Dann wahrscheinlich in der rechten unteren Ecke, wo auch externe Profilseiten verlinkt werden.
Gibt es dazu Meinungen?

**Comment by sonschul** [comment]
Find ich gut und ausreichend mit dem Logo von ORCID.

**Comment by dofeldsc** [comment]
Ist eingebaut und aufs Testsystem übertragen.
Da es bis jetzt nur eine Person mit einem ORCID-Eintrag gibt könnte ihr das nur hier sehen https://fis.virtuos.uni-osnabrueck.de/vivouos/display/n551 

Passt das so?
Wenn ihr sehen wollt wie das mit anderen Einträgen aussieht, einfach einloggen und paar Dinge hinzufügen.

**Comment by sonschul** [comment]
![image](https://user-images.githubusercontent.com/40201793/125577208-c4f81a94-2c15-4247-aee0-6d628b952287.png)

Ich fände es linksbündig unter den Schwerpunkten besser. 
Von der Optik sonst in Ordnung. 
Allerdings wurde ich in anderen Kontexten immer mal wieder darauf aufmerksam gemacht, dass Inhalte/Texte immer kleiner werden und dadurch schlecht lesen oder bedient werden können. 
Wenn der Platz auf der Seite es zu lässt, dann würde ich es auch etwas größer darstellen.

**Comment by dofeldsc** [comment]
Habe ich eingebaut und spiele es nachher aufs Testsystem.
dazu aber noch ein paar Fragen:
- Da es jetzt unter den Forschungsschwerpunkten aufgelistet ist, sollte es eine Überschrift bekommen? Sonst sieht das so aus als ob es ein Forschungsschwerpunkt ist...
- wegen der Lesbarkeit, soll dann alles größer gemacht werden? Man kann ja auch selber Zoomen bzw die Seite komplett vergrößern. Der Platz ist ja immer relativ (Laptop, großer Monitor, Mobile Ansicht).

**Comment by sonschul** [comment]
Das ist eine gute Frage...

Brown University hat "In the Web" als Überschrift vorgesehen... 
Vielleicht auf Deutsch "Web Profile" und die Möglichkeit anbieten dort
- ORCID, LinkedIn, ResearchGate, Google Scholar, Twitter zu verlinken? 

Zur Größe: ich würde eher zur Größe des Profil-Namens als zur Textgröße tendieren. 
Was meint ihr?

**Comment by dofeldsc** [comment]
wie gerade besprochen:
- ORCID-Logo zum test mal etwas größer.
- Der ORCID-Link soll wieder auf die linke Seite unter "Webseiten" aufgeführt werden

**Comment by dofeldsc** [comment]
So würde das jetzt mit größerem Logo und an der neuen Stelle aussehen:
![Bildschirmfoto vom 2021-07-20 15-25-56](https://user-images.githubusercontent.com/9248706/126332005-e93cee5e-b291-4c16-a532-f0e3a2305849.png)

Also mit der Größe des Logos finde ich okay aber direkt unter Webseiten, da bräuchte es schon noch eine eigene Überschrift...oder man macht den Link auch in rot (also das ORCID), was ich aber irgendwie nicht schön fände. 
so zum Beispiel 
![Bildschirmfoto vom 2021-07-20 15-29-42](https://user-images.githubusercontent.com/9248706/126332560-e5fbb574-fb68-4c96-a186-60c5985edaf9.png)


Was meint ihr dazu?

**Comment by dofeldsc** [comment]
wie gerade besprochen kann das so bleiben. Ticket ist also erledigt
