### ISSUE TITLE
Profilseite: Mobile Ansicht der uos-vcard sieht nicht gut aus

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#112]
Mir ist gerade bei einem anderen Ticket aufgefallen das die mobile Ansicht auf der Profilseite (Personen) nicht optimal aussieht. Ich würde bei zu wenig Platz jetzt einfach erst Foto und dann den Rest anzeigen. Wäre das okay oder wie wünscht ihr euch das?

So war es bist jetzt: 
![Bildschirmfoto vom 2021-07-14 14-59-28](https://user-images.githubusercontent.com/9248706/125626353-e5f16ab4-dc99-488e-af5b-cabaeb684170.png)

Das wäre mein Vorschlag:
![Bildschirmfoto vom 2021-07-14 15-00-22](https://user-images.githubusercontent.com/9248706/125626377-6447c380-80a9-4ee1-9f8e-1bf57c715c4a.png)

**Comment by sonschul** [comment]
Viel besser so ! 

Kann man die "Suchleiste" noch linksbündig ausrichten, wie in der Vorher-Ansicht?

**Comment by dofeldsc** [comment]
Wenn die Auflösung groß genug ist ist beides nebeneinander. Da die Suchleiste eine Mindestgröße hat wird das bei zu kleiner Auflösung halt so. 
Kann ich mir anschauen, du meinst das die dann die ganze Breite einnimmt oder?

**Comment by sonschul** [comment]
Ganze Breite wäre sicherlich auch eine gute Alternative! 

Es ging hier glaub ich hauptsächlich um die Text  / Bild Aufteilung, wenn ich mich recht erinnere.

**Comment by dofeldsc** [comment]
wie gerade besprochen, passt das so. Das Ticket ist erledigt
