### ISSUE TITLE
Seite:Home / section: home-research 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#12]
Unter Forschung tauchen die Drittmittelprojekte nicht auf. 
Das TestProjekt wurde als Instanz in: Drittmittelprojekt (kdsf) angelegt. 
Vermutlich werden nur Forschungsaktivitäten der VIVO Ontology angezeigt. 

![grafik](https://user-images.githubusercontent.com/40201793/48336019-a50a5700-e65f-11e8-8388-49df7174f61f.png)

**Comment by dofeldsc** [comment]
Ich habe gerade mal nachgeschaut, die Klassen sind hart in dem Template eingefügt also man könnte das hinzufügen oder das Drittmittelprojket also die Klasse einfach als Unterklasse einer verwendeten Klassen einordnen. Also es ist möglich aber ich muss dafür mal mit jemandem sprechen der sich gut mit Ontologien auskennt.

**Comment by sonschul** [comment]
Drittmittelprojekt scheint auch bei den activites und nicht bei research eingeordnet zu sein. 
('externally funded project') und nur die unterklassen von research wie article, books werden angezeigt. Abstract funktioniert aber auch nicht.... 
In vivo habe ich keine klasse unter Research gefunden, die man dafür als Oberklasse nutzen könnte. 
Aber vielleicht kann da noch jemand von den Ontolgie-Experten helfen.

**Comment by dofeldsc** [comment]
"<#if (class.individualCount > 0) && (class.uri?contains("AcademicArticle") || class.uri?contains("Book") || class.uri?contains("Chapter") ||class.uri?contains("ConferencePaper") || class.uri?contains("Grant") || class.uri?contains("Report")) >" (lib-home-page.ftl)

Das ist die Anweisung im Code. Also müssen es mehr als 0 sein und aus einer der 6 Klassen stammen. Das könnte man also ohne große Probleme erweitern oder über die Ontologie (Klasse) lösen. Ich überlege mir mal was

**Comment by sonschul** [comment]
und wenn du mal probierst dahinter folgendes einzufügen:
|| class.uri?contains("Drittmittelprojekt"))

BTW das Label enthält einen Rechtschreibfehler. Das heißt externally funded project auf englisch:
![grafik](https://user-images.githubusercontent.com/40201793/48401861-6beae900-e72a-11e8-98ad-e0e371362dc8.png)

**Comment by dofeldsc** [comment]
Ja das das so geht ist mir bewusst :D So wie das da gemacht wurde würde man das nur generell nicht machen. Man Schreibt solche Klassen nicht hart in den Code. Wenn sich jetzt ein Klassenlabel ändert oder noch andere Klassen hinzukommen müsste man jedes mal den Code anpassen und neu bauen. Wie gesagt, ich überlege mir was

BTW ändern, commiten und dann pushen. Wenn ich mich richtig erinnere wolltet ihr eh mal die ganze Ontologie durchgehen und kontrollieren

**Comment by sonschul** [comment]
Und wo steht das englische Label?

In der Ontologie kdsf-vivo-alignment.owl nämlich nicht...

    

    <owl:Class rdf:about="http://kerndatensatz-forschung.de/owl/Basis#Drittmittelprojekt">
		<rdfs:label xml:lang="de-DE">Drittmittelprojekt</rdfs:label>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/ERO_0000014"/>
        <Meta:inhaltlicheDefinition>Dr2a</Meta:inhaltlicheDefinition>
        <Meta:inhaltlicheDefinition>Dr30</Meta:inhaltlicheDefinition>
        <obo:IAO_0000115>Drittmittelprojekte im Sinne des Kerndatensatzes sind zeitlich befristet geförderte Forschungsaktivitäten mit Startdatum, Enddatum und Forschungsgegenstand, deren Finanzierung aus Drittmitteln erfolgt.</obo:IAO_0000115>
        <vitro:hiddenFromDisplayBelowRoleLevelAnnot rdf:resource="http://vitro.mannlib.cornell.edu/ns/vitro/role#public"/>
        <vitro:hiddenFromPublishBelowRoleLevelAnnot rdf:resource="http://vitro.mannlib.cornell.edu/ns/vitro/role#public"/>
        <vitro:inClassGroup rdf:resource="http://vivoweb.org/ontology#vitroClassGroupactivities"/>
        <vitro:prohibitedFromUpdateBelowRoleLevelAnnot rdf:resource="http://vitro.mannlib.cornell.edu/ns/vitro/role#public"/>
    </owl:Class>

**Comment by dofeldsc** [comment]
Ich fürchte du bist im falschen Branch, der Standard Branch (sollte eigentlich automatisch drin sein, funktioniert hier bei uns) für uns ist uos-extension.

Und da steht folgendes:
`<owl:Class rdf:about="http://kerndatensatz-forschung.de/owl/Basis#Drittmittelprojekt">
		<rdfs:label xml:lang="de-DE">Drittmittelprojekt</rdfs:label>
        <rdfs:label xml:lang="en-US">Externally fundet project</rdfs:label>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/ERO_0000014"/>
        <Meta:inhaltlicheDefinition>Dr2a</Meta:inhaltlicheDefinition>
        <Meta:inhaltlicheDefinition>Dr30</Meta:inhaltlicheDefinition>
        <obo:IAO_0000115>Drittmittelprojekte im Sinne des Kerndatensatzes sind zeitlich befristet gefÃ¶rderte ForschungsaktivitÃ¤ten mit Startdatum, Enddatum und Forschungsgegenstand, deren Finanzierung aus Drittmitteln erfolgt.</obo:IAO_0000115>
        <vitro:hiddenFromDisplayBelowRoleLevelAnnot rdf:resource="http://vitro.mannlib.cornell.edu/ns/vitro/role#public"/>
        <vitro:hiddenFromPublishBelowRoleLevelAnnot rdf:resource="http://vitro.mannlib.cornell.edu/ns/vitro/role#public"/>
        <vitro:inClassGroup rdf:resource="http://vivoweb.org/ontology#vitroClassGroupactivities"/>
        <vitro:prohibitedFromUpdateBelowRoleLevelAnnot rdf:resource="http://vitro.mannlib.cornell.edu/ns/vitro/role#public"/>
    </owl:Class>`

**Comment by sonschul** [comment]
Danke jetzt hab ich es auch gefunden!
Leider haut mir der ATOM Editor jede Menge Leerzeilen in den Code, daher hab ich es mit dem Notepad++ probiert... Hat es geklappt?

**Comment by sonschul** [comment]
Ich hab gerade noch ein paar Änderungen der labels gepusht...
Was mache ich mit doppelten Definitionen in der kdsf-vivo-alignment wie Fach/Field oder Finanzierungsform?

**Comment by dofeldsc** [comment]
Doppelte Definitionen? Du meinst die Klasse und die Property?

**Comment by sonschul** [comment]
Besser: Divergierende Bezeichnungen! ;-) 
Bei der Klasse und beim Objectproperty wurde unterschiedlich übersetzt. 
Wäre es eventuell besser das anzugleichen?

**Comment by dofeldsc** [comment]
Ihr bzw. du kannst das so ändern wie du es gerne haben möchtest :) Bei den meisten macht es bestimmt Sinn gleiche Labels zu benutzen aber z.B. eine Beziehung zwischen Person und Raum sollte vllt nicht Raum heißen sondern sowas wie "sitzt in". Man muss schon noch den Ontologiegedanken im Kopf behalten. Eine andere Anzeige ist bei sowas auch möglich. Die Ontologie für die Kontaktdaten besteht aus einer Menge von VCards aber die Anzeige sieht ganz anders aus.
