### ISSUE TITLE
Fehler - Übersetzungen: Konzepte 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#13]
Auch auf den Konzept-Seiten taucht der Fehler auf, dass bei fehlender Übersetzung einfach irgendeine Sprache genutzt wird... Spanisch ? 

Beispiel:
https://fis.virtuos.uni-osnabrueck.de/vivouos/display/n4404

**Comment by sonschul** [comment]
![grafik](https://user-images.githubusercontent.com/40201793/48360109-c9395880-e69e-11e8-8089-de53d0cbad07.png)

**Comment by dofeldsc** [comment]
Also als Standard wird jetzt die Sprache genommen die man als Alternative angibt, in unserem Fall also Englisch. Aber generell sollten keine Labels mehr nur auf einer Sprache verfügbar sein. Dafür am besten mal ein extra Ticket mit einer Liste dieser Labels @manschwa 

=> Hat leider nur bei manchen Labels funktioniert...seltsam

**Comment by sonschul** [comment]
Die Menüleiste (Home, People, Organisationen ...) ist aber auch wieder "mehrsprachig" gemischt.

auf https://fis.virtuos.uni-osnabrueck.de/vivouos/

**Comment by sonschul** [comment]
![grafik](https://user-images.githubusercontent.com/40201793/48852109-f1b30800-edac-11e8-9ea2-2f7b6168df65.png)


"member of" hatte vorher ein deutsches Label

**Comment by dofeldsc** [comment]
ja wir probieren da gerade etwas rum, der alte Stand wird nachher aber wieder eingespielt falls das hier nicht funktionieren sollte
