### ISSUE TITLE
Personen-Suchseite / Klassen / Ansicht 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#14]
Ist es möglich die Personen-Seite in dieser Form darzustellen? 

![grafik](https://user-images.githubusercontent.com/40201793/48466885-6b645800-e7e7-11e8-9e52-58e81db49bbd.png)

**Comment by sonschul** [comment]
MEMO:

Label: Juniorprofessur - Liste der JuniorprofessorInnen / RDF local name: Juniorprofessoren
Label: Professur - Liste aller ProfessorInnen / RDF local name: OrdentlicheProfessoren 
Label: Stiftungsprofessur - Liste der StiftungsprofessorInnen RDF local name: Stiftungsprofessoren
Label: Wissenschaftliches und künstlerisches Personal - Alle ProfessorInnen inkl. Vertretungsprofessuren (RDF local name: Vertretungsprofessoren)

(Label: Programmprofessur - - kein eigener Filter - NiedersachsenprofessorInnen, Humboldt- und Heisenberg - ProfessorInnen --> evtl. in Denomination oder anderer ObjectProperty unterbringen)
(Vertretungsprofessoren - kein eigener Filter)

**Comment by dofeldsc** [comment]
Geschlossen heißt das hat sich erledigt? Die Änderungen gab es ja noch nicht, der Eintrag von mir am Ende da habe ich mich leider im Ticket vertan

**Comment by sonschul** [comment]
Vorläufig erledigt.
