### ISSUE TITLE
Skalieren der Leitlinienbilder auf der Startseite

### ISSUE THREAD

**Issue by manschwa** [FISvirtUOS/VIVO#15]
Größe der Website bisher ca. 50 MB (viel zu groß).

Leitlinienbilder unter
`/themes/tenderfoot_uos/images/`
verkleinern auf die Auflösung 365x182px

**Comment by dofeldsc** [comment]
traumhaft, ist eingebaut und läuft. Dabei ist uns aufgefallen das die Bilder nicht ordentlich angeordnet sind (wahrscheinlich alter css fix überschrieben).
Ich hänge das an ein anderes Ticket damit wir dieses hier schließen können.
