### ISSUE TITLE
Fehler: Mittelgeber der Projekte

### ISSUE THREAD

**Issue by ghost** [FISvirtUOS/VIVO#16]
Bei Anklicken der Kdsf-Mittelgeber ""Nicht erklärte private Mittelgeber" und "Nicht erklärte öffentliche Mittelgeber" innerhalb der Projektseite erscheint: "Datensatz nicht gefunden".

**Comment by dofeldsc** [comment]
Ja weil die so clever waren und Umlaute mit in die URIs genommen haben. Die Instanzen kommen aus der KDSF Ontology  und existieren zwar im System aber sobald man versucht diese zu linken werden die Umlaute aus der URI gelöscht und der Link funktioniert nicht. Also muss man in den KDSF-Ontologien einfach den internen Namen der Instanzen anpassen. 
Machst du das oder soll ich?

**Comment by dofeldsc** [comment]
Ich habe es abgeändert, auf dem Testserver eingespielt und getestet. Passt alles
