### ISSUE TITLE
Schlagwörter nicht Teil der Suche (Finden Sie einen Experten)

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#17]
Reminder: Wir hatte schon kurz darüber gesprochen, dass die Suche noch weitere Teile der Personenprofile beinhalten soll. Darunter vor allem:

- Schlagwörter
- Denomination
- Art der Professur (ehemals Bezeichnung der Professur)
- Fach

**Comment by dofeldsc** [comment]
Also bei mir werden die berücksichtigt. Ich habe das unter https://fis.uni-osnabrueck.de/vivouos mit der Testperson ausprobiert. Wenn man die richtige Syntax (*) bei Substrings benutzt werden auch die gefunden. Funktioniert das bei dir nicht?

**Comment by dofeldsc** [comment]
Funktioniert. Anpassung der Hilfeseite für Erklärung der Syntax "*Suchbegriff*" wird über separates Ticket eingefügt.
