### ISSUE TITLE
Personen-Übersicht - Text abgeschnitten "Vertretungsprofessor/Lehrstuhlvertreter"

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#18]
![grafik](https://user-images.githubusercontent.com/40201793/48839697-92450000-ed8c-11e8-8a91-316fffe94672.png)

**Comment by dofeldsc** [comment]
Etwas Text wäre nett aber du meinst wahrscheinlich das Vertretungsprofessor/Lehrstuhlvertreter nicht umgebrochen wird oder?
Das liegt an deinen Änderungen in der KDSF Ontologie vom 13.11.

**Comment by sonschul** [comment]
Änderungen nehme ich wie besprochen zurück!
Edit: Änderungen mit github commited und auch schon gepushed.
