### ISSUE TITLE
Erstellung eines Themes für die Universität Osnabrück

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#2]
Erste besprochene Anforderungen:
- [x] Header der Website mit dem Unilogo auf uniroten (#AD2034) Grund designed werden soll. Das VIVO-Logo kann daneben eingefügt werden
- [x] Zudem soll das Layout des Systems in Gänze dem Corporate Design der Uni angepasst
- [x] Der Wilkommensslogan soll in "Wilkommen auf VIVO@UOS/ Welcome to VIVO@UOS" geändert werden
- [x] Zusätzlich soll ein Begrüßungstext in englisch und deutsch verfasst und integriert werden (wer macht das?)
- [x] Das Element "Geo-Focus/Location" soll vorerst rausgenommen werden, da noch zu wenige Geo-Daten vorliegen
- [x] Zusätzlich soll - ähnlich wie bei der TiB - ein Element integriert werden, in dem die 6 Profillinien der Uni durch Bilder abgebildet werden. Die Bilder sollen der Uni-Website entnommen werden
- [x] Der "About VIVO"-Text soll durch einen FIS-Textabschnitt ergänzt werden 
- [x] Die Profilseite soll ebenfalls an das CD angepasst werden
- [x] Die Kategorie "Professor" soll unter den Titel+Namen gesetzt werden. Darunter die Denomination und darunter ein Reiter mit "Statistics" in dem die Anzahl der veröffentlichten Publikationen, etc. sichtbar werden
- [x] Die Kategorie "hat Vertrag" wurde falsch konfiguriert und muss noch überarbeitet werden. Der Zusatz "hat" vor den einzelnen Kategorien soll - wenn möglich - rausgenommen werden, ebenso wie der Zusatz "Organisationseinheit/Division" innerhalb der Kategorie "Organisationseinheit"
- [x] Farbe der Buttons und der Bilder stimmt nicht genau überein, prüfen
- [x] Es wurden neue Bilder für die Titelseite und zwei Profile geliefert, einbauen

So viel zum ersten Stand, es wird im Issue noch weitergeführt.

**Comment by dofeldsc** [comment]
Der Begrüßungstext bleibt erstmal wie er ist (in Absprache mit ZBW)

**Comment by dofeldsc** [comment]
Für die Erstellung einer "eigenen" Profilseite für bestimmte Klassen bietet sich diese Anleitung an: 
https://wiki.duraspace.org/display/VIVODOC19x/Class-specific+templates+for+profile+pages

Das neue Template kann man dann im Theme-Ordner unter "templates/body/individual" ablegen und es wird geladen (für kdsf:Professor erledigt)

**Comment by dofeldsc** [comment]
Das Treffen am 28.05 hat noch folge Punkte ergeben:
Startseite:
- [x] VIVO-Header verkleinern -> das Vivo logo ist gemeint
- [x] Profillinienbilder tauschen und Hintergrund der "Überschrift" transparenter machen
- [x] Schwarzer Balken am Ende der Website in unigrau ändern

Profilseite (kdsf-Prof):
- [x] Kategorie "Professor" unter Name setzen, darunter die Denomination verschieben, darunter Statistics mit Anzahl an Publikationen, etc. setzen
- [x] "hat" vor den Kategorien löschen
- [x] "Organisationseinheit/Division" in Kategorie "Organisationseinheit" löschen
- [x] farbliche Anpassung im Rahmen des CD
- [x] Anordnung/Ausrichtung der Bilder (Profillinien) auf der Startseite fixen

**Comment by ghost** [comment]
Ich hoffe, ich lege das hier jetzt richtig an. Was schon erledigt ist bitte einfach abhaken. Wie gestern besprochen sind noch folgende Aufgaben zu erledigen:

- [x] Startseite: Button: "Alle anzeigen" in Uni-rot

- [x] Home-/Search-Icons einpflegen (Jesko nach Vorlage fragen)

- [x] Personenseite: "Konzepte" in rot anstatt blau (bisher noch keine Konzepte angelegt)

- [x] Layout auf allen Seiten: Kantige/eckige Formen, anstatt runder

- [x] Footer: Scrollbar soll verschwinden

- [x] Übersichtsseiten: grüner Preil -> rot, blauer Text -> fett und dunkel grau
