### ISSUE TITLE
home und search icons austauschen

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#20]
Auf https://fontawesome.com/ gibt es free Icons, die man als stylesheet im `<head>` bei bootstrap Projekten einfügen kann. Hätte den Vorteil, dass man sie vor beliebigen Hintergründen und Größen nutzen kann. (gibt es aber auch zum Download, falls das gewünscht ist) 

Lupe: https://fontawesome.com/icons/search?style=solid
Haus: https://fontawesome.com/icons/home?style=solid

Und ja, ich weiß, dass es nicht exakt die Icons von der Uni-Homepage sind! ;-)

**Comment by sonschul** [comment]
Erledigt, oder? @manschwa

**Comment by manschwa** [comment]
Ja, ist erledigt, siehe
https://github.com/FISvirtUOS/VIVO/commit/0e1c4c7526cf6ba3d95b569b9414bb6652b3727a
und
https://github.com/FISvirtUOS/VIVO/commit/f16b82ede5902703a9b380e4890950c9b7225821
