### ISSUE TITLE
Anpassungen der Ontologie KDSF bzw. UOS-Core (Verlagsort) 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#21]
Sollen Änderungen lieber in der KDSF-Ontologie oder im UOS-Core vorgenommen werden? 

Ontology: KDSF-VIVO-Alignment
Klasse: Verlag (kdsf)
--> Verlagsort 

Der Klasse Verlag (kdsf) (äquivalent zu Publisher (vivo)) sollte eine weitere Eigenschaft namens "Verlagsort" zugewiesen werden, die als Ausprägungen nur ein Literal (String) enthalten soll. Einem Verlag scheinen mehrere Verlagsorte zugeordnet werden zu können. 
Die Definition des Verlagsorts ist in den Spezifikationen des KDSF unter "Pu153" zu finden.

**Comment by dofeldsc** [comment]
Eigentlich füge ich Dinge immer gerne in unsere eigene Ontologie ein damit wir nicht zu sehr vom Stand der Community abweichen aber das gehört ja deutlich zum KDSF. 
Ich schick den eh bald mal unsere Überarbeitungen.

Ich habe es jetzt dem KDSF hinzugefügt und würde den aktuellen Stand gleich auf den Server spielen. 

Was hättest du gern als englisches Label? "publishing place"?

**Comment by sonschul** [comment]
Im Harvard Referencing Guide heißt es "place of publication". Lieber so benennen!

**Comment by dofeldsc** [comment]
Alles klar, ich spiele es gerade ein
