### ISSUE TITLE
Capability Map und Map of Science (beides übersetzt als Wissenschaftslandkarte) 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#22]
Inhaltlich zwar nicht das gleiche, aber beides in MiniVIVO auf Grund fehlender Eingaben nicht funktionstüchtig. Wir sollten überlegen diese Funktionen vorübergebend zu deaktivieren.

**Comment by dofeldsc** [comment]
Deswegen wurde der Menüpunkt ja zu Fähigkeitskarte geändert aber die Änderung wolltest du wieder rückgängig gemacht haben. 
Den Punkt im Menü kann man über die Einzelseitenverwaltung entfernen.
Den anderen Fall auf der Profilseite wollte Manuel sich anschauen. Müsst nur sagen ob wir entfernen sollen oder nicht.

**Comment by sonschul** [comment]
Dann nehme ich den Menüpunkt erstmal raus über die Einzelseitenverwaltung auf fis.uni-osnabrueck.de und wir schauen uns das für das nächste Release an.
