### ISSUE TITLE
Publikationsgrafik

### ISSUE THREAD

**Issue by ghost** [FISvirtUOS/VIVO#23]
Die Grafik "Publikationen in VIVO" auf der Personenseite (von Personen, die eine Publikation vorzuweisen haben) wird noch falsch angezeigt. Die Skalierung beginnt "abgehackt" bei 0,3.

**Comment by dofeldsc** [comment]
Bei denen die ich mir jetzt gerade angeschaut habe nicht...Hast du mal ein Beispiel für mich?

**Comment by sonschul** [comment]
https://fis.uni-osnabrueck.de/vivouos/display/CeRa138

![grafik](https://user-images.githubusercontent.com/40201793/49727247-08dc6b80-fc70-11e8-81e2-167217bcda62.png)

**Comment by dofeldsc** [comment]
![abbildung_publikationen](https://user-images.githubusercontent.com/9248706/49728221-75586a00-fc72-11e8-9b1e-09afc42940b6.png)
seltsam, ist bei mir nicht so. Die Grafiken werden immer für jeden Client neu erstellt aber mehr habe ich mir dazu noch nicht angeschaut.

**Comment by dofeldsc** [comment]
Ist ein Problem vom Browser (Firefox Version 63.0.3 (64-Bit) getestet). Wenn man der SVG-Grafik einfach mehr Höhe gibt das würde das auch passen. Grafik ist also in Ordnung, wird nur falsch angezeigt (zu klein)

**Comment by dofeldsc** [comment]
Fehler gelöst, das war ein Problem mit einer Funktionalität des D3.js Frameworks.
