### ISSUE TITLE
Menüsortierung

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#24]
Laut DuraSpace müsste es eine Funktion für die Menüsortierung geben. 
Dort kann man mit Drag&Drop die Seiten neu anordnen. 
Wird das nur bei mir nicht korrekt geladen, oder funktioniert das grundsätzlich nicht? 

https://wiki.duraspace.org/display/VIVODOC110x/Menu+and+page+management

**Comment by dofeldsc** [comment]
Ja das ist gerade leider kaputt, es gibt schon eine eingebaute Lösung aber bis jetzt in keiner Release Version. Kommt also wahrscheinlich mit dem nächsten Vivo Patch

https://jira.duraspace.org/browse/VIVO-1613?src=confmacro
