### ISSUE TITLE
Untertitel auf Seite "Organisationen" für Fachbereiche / Institute ausblenden

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#25]
Da als Untertitel in der Liste noch "Academic Department" und "Institute" angezeigt werden und nicht die deutschen Klassenbezeichnungen, wäre es schön, wenn die Untertitel wie bei der Seite für das "Fach" ausgeblendet werden.

**Comment by dofeldsc** [comment]
erledigt durch eigene ShortView für foaf:Organisation und alle Unterklassen
