### ISSUE TITLE
Projektergebnisse neu laden (fehlerhafte DOI)

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#28]
Projektergebnisse neuladen wegen Fehler in der DOI Spalte. 

![image](https://user-images.githubusercontent.com/40201793/49881862-3586b380-fe27-11e8-91ea-3704c0c6cb8c.png)

Siehe dazu auch neue Datei in Mail von Marco

**Comment by dofeldsc** [comment]
DOI wurden angepasst, ISBN13 hinzugefügt und die externe URL wird abgebildet. Die Ontologie wurde um eine Property "externe URL" für kdsf:Publikationen ergänzt. 

Kann ich davon ausgehen das die ISBN immer alsd ISBN13 angeliefert wird oder kann auch die 10-Variante vorkommen. In der aktuellen Liste war jetzt nur die ISBN13 dabei also passt das erstmal.

Daten sind upgedatet!
