### ISSUE TITLE
Begrüßungstext auf Startseite austauschen

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#29]
Unter dem Suchformular auf der Startseite bitte den folgenden Text einfügen:

"Mit VIVO wird Ihnen ein forschungsorientiertes Recherchewerkzeug zur Verfügung gestellt, mit dem Sie Einblick in wesentliche Informationen zu ausgewählten Drittmittelprojekten und daraus hervorgegangenen Forschungsergebnissen erhalten können, die im Rahmen der niedersächsischen Leitlinien zur Transparenz in der Forschung veröffentlicht werden sollen. 

Bei Ihrer Recherche unterstützen Sie die ausgewiesenen Kategorien – Sie können aber auch gezielt Informationen wie zu bestimmten Drittmittelprojekten, Personen, Fachbereichen, Instituten/Seminaren und/oder Veranstaltungen suchen."

**Comment by dofeldsc** [comment]
Kannst du den Text bitte auch direkt in englisch hinterlegen? Ich würde solche Inhalte ungern nur in einer Sprache einbauen. Ich integriere das dann direkt in die i18n-Dateien.

**Comment by sonschul** [comment]
Schaffe ich heute nicht mehr... :-/ 
Kannst du das ausnahmsweise nur in deutsch einbauen?

**Comment by dofeldsc** [comment]
Ist schon eingebaut aber wir sollten dran denken, nicht das irgendwer auf englisch umschaltet und dann steht da ein anderer Text.

**Comment by sonschul** [comment]
Ich würde gerne ein paar der Fließtexte sammeln und professionell übersetzen lassen. 
Falls euch an anderer Stelle noch Texte auffallen, die übersetzt werden sollten, dann sag mir bitte Bescheid!

**Comment by dofeldsc** [comment]
Die Terms of Use bzw. Nutzungsbedingungen sind auch nur auf englisch, haben wir ja gerade schon drüber gesprochen aber auf Dauer wäre das bestimmt nicht schlecht das zu übersetzen.

**Comment by sonschul** [comment]
Müssen bei den Terms of Use noch Anpassungen für die Uni Os vorgenommen werden? 
Sonst würde ich mich darum kümmern, dass die Übersetzungen in Auftrag gegeben werden.

**Comment by dofeldsc** [comment]
Nicht das ich wüsste. Gerade nochmal durchgelesen aber mir ist persönlich nichts aufgefallen. Kann also gerne übersetzt werden. Haben wir sonst noch was?
