### ISSUE TITLE
Last Minute Wünsche für Präsentation (Anpassung Projektprofil)

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#30]
Auf der Seite der Projekte wäre es schön, wenn die folgenden drei Punkte noch geändert werden: 

- [x] false bei Koordinatorenrolle ausblenden. Im Prinzip kann auch die ganze Katgeorie raus, weil bei allen "false" steht

- [x] Den Text "Fach" (Klasse) hinter dem eigentlichen Fach raus

- [x] Academic Department raus 

![image](https://user-images.githubusercontent.com/40201793/49932209-c5306e80-fec8-11e8-9b80-8a3682fd6c70.png)

Was bis morgen geht geht, was nicht geht, geht halt nicht...

**Comment by dofeldsc** [comment]
Für alle drei Properties eine eigene ListView hinzugefügt.
Für die Properties "Fach" und "Organisationseinheit" wurde der Klassenname entfernt. Für "Koordinationsrolle" wurde von true und false auf ja  und nein gewechselt. Direkt auch für die Mehrsprachigkeit (bis jetzt nur englisch) hinzugefügt.
Wenn die Koordinationsrolle komplett ausgeblendet werden soll, kann das in der kdsf-Ontologie geändert werden. Ich lasse es jetzt erstmal drin.
