### ISSUE TITLE
Externe Projektseite als Link einbetten

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#31]
![image](https://user-images.githubusercontent.com/40201793/49932543-9666c800-fec9-11e8-9ef3-de20663b7ceb.png)

z.Z. nicht anklickbar

**Comment by dofeldsc** [comment]
Das ist ein generelles Vivo Problem und steht auch schon auf den Roadmap aber eigentlich bis Ende diesen Jahres also kein Ahnung wann das kommt (https://wiki.duraspace.org/display/DSPACE/End+User%3A+URLs+are+clickable+links+in+metadata+fields).

Ich habe jetzt mal eine eigene Lösung für diese Property und die neue "externe URL" bei Publikationen eingebaut. Bei Gelegenheit mal schauen ob ich das nicht direkt für alle Properties vom Typ URL/URI machen kann.
