### ISSUE TITLE
add text block to default template (menu page)

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#33]
Anpassen des default-templates
Unterhalb der `<h2>` überschrift in der section = "menupage-intro" soll ein hilfetext mit erklärungen zur jeweiligen klasse auftauchen.

**Comment by sonschul** [comment]
- Auf der Personen-Seite folgenden Text: 
"Derzeit sind zum 31.12.2017 an der Universität Osnabrück beschäftigte Mitglieder der Hochschullehrergruppe mit jeweiligem Status im System abgebildet. Abgebildet sind zudem zum Stichtag beschäftigte wissenschaftliche Mitarbeiterinnen und Mitarbeiter, sofern diese an in den Jahren 2015 und 2016 abgeschlossenen drittmittelfinanzierten Projekten beteiligt waren. Im System abgebildet werden zudem jene Projektverantwortliche, die am 31.12.2017 nicht mehr an der Universität beschäftigt waren, aber für zum Stichtag 1.12.2015 laufende und bis 2017 abgeschlossen, drittmittelfinanzierte Projekte verantwortlich bzw. an diesen Projekten beteiligt waren.
Im Laufe des akademischen Jahres 2019 werden diese Informationen sukzessive um Beschäftigte bzw. an drittmittelfinanzierten Projekten Beteiligte ergänzt."  

- Auf der Projekt-Seite folgenden Text: 
"Derzeit werden mit Blick auf die landesseitigen Anforderungen zur Transparenz der Forschung zunächst nur zum Stichtag 1.12.2015 laufende und bis 31.12.2017 abgeschlossene, drittmittelfinanzierte Projekte im System abgebildet. Unter Beachtung etwaiger Vertraulichkeitsregelungen wird Aufschluss gegeben über die institutionelle Verortung, den Titel, die Laufzeit, die Fördersumme, die Auftraggeberin oder den Auftraggeber sowie über die jeweils erzielten Ergebnisse dieser drittmittelfinanzierten Projekte. 
Im Laufe des akademischen Jahres 2019 werden diese Informationen sukzessive über am 1.12.2016 bis 1.12.2018 laufende, drittmittelfinanzierte Projekte ergänzt."

- Auf der Publikations-Seite folgenden Text: 
"Derzeit werden mit Blick auf die landesseitigen Anforderungen zur Transparenz der Forschung zunächst nur Publikationen abgebildet, die als Forschungsergebnisse aus zum Stichtag 1.12.2015 laufende und bis 31.12.2017 abgeschlossene, drittmittelfinanzierte Projekten hervorgegangen sind. 

- Die Seite zu den Organisationen braucht keinen Hinweistext. Oder sieht das im Template blöd aus ohne Text? 

- Kann der folgende Text noch unter dem Über VIVO Text hinzugefügt werden? 
" **Über VIVO an der Universität Osnabrück**

Ziffer 12 der Zielvereinbarung 2014-2018 der niedersächsischen  Hochschulen mit dem Land Niedersachsen und entsprechende landesseitige »Leitlinien zur Transparenz in der Forschung« verpflichten die Hochschulen seit 2016, die Öffentlichkeit an exponierter Stelle ihres Internetauftritts unter Beachtung etwaiger Vertraulichkeitsregelungen jährlich über die institutionelle Verortung, den Titel, die Laufzeit, die Fördersumme, die Auftraggeberin oder den Auftraggeber sowie ab Ende 2018 über die jeweils erzielten Ergebnisse drittmittelfinanzierter Projekte zu informieren. Die grundlegenden Daten zu drittmittelfinanzierten Projekten sind erstmalig mit Stichtag 1.12.2015 am 31.3.2016 veröffentlicht worden und werden seither an der Universität Osnabrück jährlich mit dem Stichtag 1.12. eines jeden Jahres im darauffolgenden Jahr excelbasiert im nicht barrierefreien pdf-Format ins Netz gestellt. 
Seit November 2017 ist die Open Source Software VIVO  an der Universität Osnabrück anforderungsorientiert weiterentwickelt worden, zunächst um die Öffentlichkeit anforderungsentsprechend aber auch nutzerfreundlich und barrierefrei über Forschungsergebnisse der zum Stichtag 1.12.2015 laufenden, drittmittelfinanzierten und bis 1.12.2017 abgeschlossenen Projekte informieren zu können. 
Im Laufe des akademischen Jahres 2019 werden diese Informationen sukzessive über am 1. 12. 2016 bis 1. 12. 2018 laufende, drittmittelfinanzierte Projekte und vorliegende Forschungsergebnisse ergänzt, wobei letztlich Ziel ist, Forschungsaktivitäten der Universität aktuell und vollständig abzubilden und nicht nur auf drittmittelfinanzierte Forschungsprojekte zu fokussieren.
Mit VIVO als integriertem Informationssystem sollen Forschungsinformationen an der Universität Osnabrück somit unter Beachtung der EU-Datenschutzgrundverordnung 
‒	historisiert, z.B. um Werdegänge von Wissenschaftlerinnen und Wissenschaftlern zu dokumentieren; 
‒	aufbereitet, z.B. durch vollständige Angabe von Projekttiteln statt Nutzung von Kurzformen;
‒	validiert, z.B. durch Abgleich mit DFG-GEPRIS-Angaben;
‒	aggregiert und logisch miteinander verknüpft, (z.B. um Personen zu Projekten und Publikationen zuzuordnen);
‒	in Anlehnung an den Kerndatensatz Forschung  des Wissenschaftsrats standardisiert
und 
‒	barrierefrei bereitgestellt werden.
Das Forschungsinformationssystem wird neben der internen Hochschulsteuerung vor allem der internen und externen Berichterstattung dienen. Ziel ist, die Außendarstellung und Reputation durch Sichtbarmachung und Präsentation von Forschungsaktivitäten sowie durch eine einheitliche Darstellung von Forscherinnen- und Forscherprofilen bzw. Forschungsprojekten im Rahmen des Corporate Designs verbessern zu können und durch Generierung eines Expertinnen- und Expertenportals die Kontaktaufnahme, den fachliche Austausch und die Kommunikation mit der Öffentlichkeit zu befördern."

**Comment by sonschul** [comment]
@MarcoSeegers : bitte die Texte quer lesen, vor allem hinsichtlich der Datums-Angaben, ob alles korrekt ist. 
@manschwa : bitte warten bis Marco die Texte freigegeben hat.

**Comment by ghost** [comment]
Habe paar Sachen angepasst und kann jetzt so eingebunden werden @manschwa .

Personen: 
"Derzeit sind zum 31.12.2017 an der Universität Osnabrück beschäftigte Professorinnen und Professoren mit jeweiligem Status im System abgebildet. Abgebildet sind zudem zum Stichtag beschäftigte wissenschaftliche Mitarbeiterinnen und Mitarbeiter, sofern diese an in den Jahren 2015 und 2016 abgeschlossenen drittmittelfinanzierten Projekten beteiligt waren. Im System abgebildet werden zudem jene Projektverantwortliche, die am 31.12.2017 nicht mehr an der Universität beschäftigt waren, aber für zum Stichtag 1.12.2015 laufende und bis 2017 abgeschlossene drittmittelfinanzierte Projekte verantwortlich bzw. an diesen Projekten beteiligt waren.
Im Laufe des akademischen Jahres 2019 werden diese Informationen sukzessive um wissenschaftliche Mitarbeiterinnen und Mitarbeiter bzw. an drittmittelfinanzierten Projekten Beteiligte ergänzt."

Projekte:
"Derzeit werden mit Blick auf die landesseitigen Anforderungen zur Transparenz der Forschung zunächst nur zum Stichtag 1.12.2015 laufende und bis 31.12.2017 abgeschlossene drittmittelfinanzierte Projekte im System abgebildet. Unter Beachtung etwaiger Vertraulichkeitsregelungen wird Aufschluss gegeben über die institutionelle Verortung, den Titel, die Laufzeit, die Fördersumme, die Klassifizierung der Mittelgeber sowie über die jeweils erzielten Ergebnisse dieser drittmittelfinanzierten Projekte.
Im Laufe des akademischen Jahres 2019 werden diese Informationen sukzessive über am Stichtag 1.12.2018 laufende drittmittelfinanzierte Projekte ergänzt."

Publikationen:
"Derzeit werden mit Blick auf die landesseitigen Anforderungen zur Transparenz der Forschung zunächst nur Publikationen abgebildet, die als Forschungsergebnisse aus zum Stichtag 1.12.2015 laufenden und bis 31.12.2017 abgeschlossenen drittmittelfinanzierten Projekten hervorgegangen sind. Im Zuge der Integrierung der am Stichtag 1.12.2018 laufenden drittmittelfinanzierten Projekten werden ggf. vorhandene Publikationen mit aufgenommen."

•	Die Seite zu den Organisationen braucht keinen Hinweistext. Oder sieht das im Template blöd aus ohne Text?

Kann der folgende Text noch unter dem Über VIVO Text hinzugefügt werden?
" Über VIVO an der Universität Osnabrück
Ziffer 12 der Zielvereinbarung 2014-2018 der niedersächsischen Hochschulen mit dem Land Niedersachsen und entsprechende landesseitige »Leitlinien zur Transparenz in der Forschung« verpflichten die Hochschulen seit 2016, die Öffentlichkeit an exponierter Stelle ihres Internetauftritts unter Beachtung etwaiger Vertraulichkeitsregelungen jährlich über die institutionelle Verortung, den Titel, die Laufzeit, die Fördersumme, die Auftraggeberin oder den Auftraggeber sowie ab Ende 2018 über die jeweils erzielten Ergebnisse drittmittelfinanzierter Projekte zu informieren. Die grundlegenden Daten zu drittmittelfinanzierten Projekten sind erstmalig mit Stichtag 1.12.2015 am 31.3.2016 veröffentlicht worden und werden seither an der Universität Osnabrück jährlich mit dem Stichtag 1.12. eines jeden Jahres im darauffolgenden Jahr excelbasiert im nicht barrierefreien pdf-Format ins Netz gestellt.
Seit November 2017 ist die Open Source Software VIVO an der Universität Osnabrück anforderungsorientiert weiterentwickelt worden. Zunächst um die Öffentlichkeit anforderungsentsprechend, nutzerfreundlich und barrierefrei über Forschungsergebnisse der zum Stichtag 1.12.2015 laufenden drittmittelfinanzierten und bis 1.12.2017 abgeschlossenen Projekte informieren zu können.
Im Laufe des akademischen Jahres 2019 werden diese Informationen sukzessive über am 1.12.2018 laufende drittmittelfinanzierte Projekte und vorliegende Forschungsergebnisse ergänzt. Letztliches Ziel ist es Forschungsaktivitäten der Universität aktuell und vollständig abzubilden und nicht nur auf drittmittelfinanzierte Forschungsprojekte zu fokussieren.
Mit VIVO als integriertem Informationssystem sollen Forschungsinformationen an der Universität Osnabrück somit unter Beachtung der EU-Datenschutzgrundverordnung
‒ historisiert, z.B. um Werdegänge von Wissenschaftlerinnen und Wissenschaftlern zu dokumentieren;
‒ aufbereitet, z.B. durch vollständige Angabe von Projekttiteln statt Nutzung von Kurzformen;
‒ validiert, z.B. durch Abgleich mit DFG-GEPRIS-Angaben;
‒ aggregiert und logisch miteinander verknüpft, (z.B. um Personen zu Projekten und Publikationen zuzuordnen);
‒ in Anlehnung an den Kerndatensatz Forschung des Wissenschaftsrats standardisiert
und
‒ barrierefrei bereitgestellt werden.
Das Forschungsinformationssystem wird neben der internen Hochschulsteuerung vor allem der internen und externen Berichterstattung dienen. Ziel ist es die Außendarstellung und Reputation durch Sichtbarmachung und Präsentation von Forschungsaktivitäten sowie durch eine einheitliche Darstellung von Forscherinnen- und Forscherprofilen bzw. Forschungsprojekten im Rahmen des Corporate Designs verbessern zu können. Zudem wird durch die Generierung eines Expertinnen- und Expertenportals die Kontaktaufnahme, der fachliche Austausch und die Kommunikation mit der Öffentlichkeit befördert werden."

**Comment by dofeldsc** [comment]
Ich habe es jetzt mal eingebaut. Auch diese Texte sollten dann demnächst ins Englische übersetzt werden damit wir die nachtragen können. Zur Übersicht wäre ein extra Ticket bestimmt nicht verkehrt.

**Comment by ghost** [comment]
Die neuen Infotexte für das Mini-Mini-VIVO:

Personen:
"Derzeit abgebildet sind Professorinnen und Professoren und wissenschaftliche Mitarbeiterinnen und Mitarbeiter, sofern diese an in den Jahren 2015 und 2016 abgeschlossenen drittmittelfinanzierten Projekten beteiligt waren. Zudem werden jene Projektverantwortliche, die am 31.12.2017 nicht mehr an der Universität beschäftigt waren, aber für zum Stichtag 1.12.2015 laufende und bis 2017 abgeschlossene drittmittelfinanzierte Projekte verantwortlich bzw. an diesen Projekten beteiligt waren, abgebildet."

Projekte:
"Derzeit werden mit Blick auf die landesseitigen Anforderungen zur Transparenz der Forschung zum Stichtag 1.12.2015 laufende und bis 31.12.2017 abgeschlossene drittmittelfinanzierte Projekte im System abgebildet. Unter Beachtung etwaiger Vertraulichkeitsregelungen wird Aufschluss gegeben über die institutionelle Verortung, den Titel, die Laufzeit, die Fördersumme, die Klassifizierung der Mittelgeber sowie über die jeweils erzielten Ergebnisse dieser drittmittelfinanzierten Projekte."

Publikationen:
"Derzeit werden mit Blick auf die landesseitigen Anforderungen zur Transparenz der Forschung zunächst Publikationen abgebildet, die als Forschungsergebnisse aus zum Stichtag 1.12.2015 laufenden und bis 31.12.2017 abgeschlossenen drittmittelfinanzierten Projekten hervorgegangen sind."
Über VIVO an der Universität Osnabrück:

„Ziffer 12 der Zielvereinbarung 2014-2018 der niedersächsischen Hochschulen mit dem Land Niedersachsen und entsprechende landesseitige »Leitlinien zur Transparenz in der Forschung« verpflichten die Hochschulen seit 2016, die Öffentlichkeit an exponierter Stelle ihres Internetauftritts unter Beachtung etwaiger Vertraulichkeitsregelungen jährlich über die institutionelle Verortung, den Titel, die Laufzeit, die Fördersumme, die Auftraggeberin oder den Auftraggeber sowie ab Ende 2018 über die jeweils erzielten Ergebnisse drittmittelfinanzierter Projekte zu informieren. Die grundlegenden Daten zu drittmittelfinanzierten Projekten sind erstmalig mit Stichtag 1.12.2015 am 31.3.2016 veröffentlicht worden und werden seither an der Universität Osnabrück jährlich mit dem Stichtag 1.12. eines jeden Jahres im darauffolgenden Jahr excelbasiert im nicht barrierefreien pdf-Format ins Netz gestellt.
Seit November 2017 ist die Open Source Software VIVO an der Universität Osnabrück anforderungsorientiert weiterentwickelt worden. Zunächst um Öffentlichkeit anforderungsentsprechend, nutzerfreundlich und barrierefrei über Forschungsergebnisse der zum Stichtag 1.12.2015 laufenden drittmittelfinanzierten und bis 1.12.2017 abgeschlossenen Projekte informieren zu können.
Letztliches Ziel ist es Forschungsaktivitäten der Universität aktuell und vollständig abzubilden und nicht nur auf drittmittelfinanzierte Forschungsprojekte zu fokussieren.“

**Comment by dofeldsc** [comment]
Ist das jetzt schon der neue Text für das "Mini-Mini-Vivo"? Falls ja, baue ich den gerne ein. Wie ist der Stand der englischen Übersetzungen?

**Comment by ghost** [comment]
Es war der aktuelle Stand bis heute :laughing: 
Muss den nochmal überarbeiten, poste den dann aber auch wieder hier.

**Comment by dofeldsc** [comment]
alles klar, dann warte ich mit dem einbauen :)

**Comment by dofeldsc** [comment]
Zur Zeit haben wir ja nur noch die drei Seiten "Leitlinien", "Drittmittelfinanzierte Projekte" und "Forschungsergebnisse" (noch nicht im Produktivsystem).
Sollen die Texte noch aktualisiert werden bevor das nächste Woche präsentiert wird?

**Comment by sonschul** [comment]
Mein Vorschlag wäre die Hilfetexte auf der Übersichtsseite zu den "Leitlinien" zusammenzufassen und auf den Seiten "Drittmittelfinanzierte Projekte" und "Forschungsergebnisse" nur noch unter der Überschrift einen Link zu der Leitlinien-Seite einzublenden statt so viel Text.

**Comment by dofeldsc** [comment]
Wie gerade mit Sonja abgesprochen, bleibt das fürs erste so. Falls andere Texte gewünscht sind oder diese auf der Leitlinien-Seite zusammengefasst werden sollen einfach das Ticket neu öffnen und die entsprechenden Texte beifügen.

**Comment by sonschul** [comment]
Bitte bei Gelegenheit auf der Projekt-Übersichtsseite im Textblock hinzufügen Transparenz "in" der Forschung. Frau Brüggemann bittet darum, dass die Leitlinien möglichst immer gleich benannt werden.
