### ISSUE TITLE
menu page ordering 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#35]
Leider funktioniert die Menüsortierung über den Site Admin nicht, daher meine Bitte, die Seiten wie folgt anzuordnen: 

Home | Leitlinien | Drittmittelfinanzierte Projekte | Forschungsergebnisse 

Die Seiten habe ich auf der virtuos / vivouos Instanz angelegt.

**Comment by dofeldsc** [comment]
Jo das ist ein bekannter Bug der auch schon gefixt wurde: https://jira.duraspace.org/browse/VIVO-1613?src=confmacro

Ich muss mal schauen wann ich die aktuellen Änderungen der Community mal wieder einspiele und ob das überhaupt schon für die 1.10 als Hotfix verfügbar ist. Das hat ja noch Zeit bis wir das "Mini-Mini-Vivo" veröffentlichen oder?
