### ISSUE TITLE
infotext der search field box auf startseite ändern

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#36]
Da wir keinen Anspruch darauf erheben alle Prof. abzubilden, würde ich vorschlagen den Text in der Suchbox (Startseite - oben rechts) zu ändern: 

`<input id="search-field-box" type="text" class="form-control" name="querytext" value="" placeholder="Durchsuchen Sie die Projekte" autocapitalize="off">`

**Comment by dofeldsc** [comment]
Aber es werden ja trotzdem alle Dinge durchsucht die im System sind also auch Personen...da passt "Durchsuchen Sie die Projekte" ja auch nicht wirklich oder?

Nett das du das html mitschickst aber das läuft dann über die Sprachdateien. Das sieht so aus 
<input id="search-field-box" type="text" class="form-control" name="querytext" value="${querytext!}" placeholder='${i18n().find_expert}' autocapitalize="off"> 
Also wollte ihr in den Sprachdateien das "find_expert" geändert haben. Was soll da auf englisch stehen?

**Comment by sonschul** [comment]
Das ist richtig, aber wir können es ja nicht mehr als Expertensuche verkaufen, wenn es gar nicht alle Professoren enthält. Daher wäre mir der andere Hilfetext lieber, auch wenn alle Inhalte durchsucht werden. Z.B. im Senat würde ich dann auch nicht mehr die "Liste aller Stiftungsprofessoren" zeigen wollen.

Das war der HTML Code aus der Chrome DevTools Ansicht... Hatte keine Ahnung, wo ich das sonst finden soll. In den Sprachdateien kenne ich mich nicht aus. 

In die Englische Übersetzung kannst du einfach "Search" reinschreiben. 
Die meisten Seiten, die ich mir angeguckt habe, haben gar nichts drin stehen. 

BTW: nicht deine Woche! ;-)

**Comment by dofeldsc** [comment]
Ich frage um sicher zu gehen. Da soll jetzt im deutschen "Durchsuchen Sie die Projekte" und im englischen "Search" stehen?

**Comment by sonschul** [comment]
Jep!

**Comment by dofeldsc** [comment]
Ist im branch "minivivo" eingebaut, davon gibt es aber gerade noch keine laufende Instanz
