### ISSUE TITLE
new class "ehemalige professoren" + new class "ehemalige mitarbeiter"

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#39]
Vorschlag: 
![image](https://user-images.githubusercontent.com/40201793/51598236-5e599880-1efd-11e9-86c5-d74a2e73c2c6.png)

**Comment by dofeldsc** [comment]
Okay, so wie du das angelegt hast wären die dann alle auch von den Klassen:
- Person
- Beschäftigte/Beschäftigter
- Wissenschaftliches und künstlerisches Personal
- ehemaliger Professor
Ist das so gewünscht? Dann kann ich die beiden gleich eben kurz einfügen. Sonst irgendwelche bestimmten Merkmale oder Sichtbarkeiten?

**Comment by sonschul** [comment]
Person (foaf) müsste reichen... 

Im VIVO core ist das für die Faculty Member Emeritus und Professor Emeritus (vivo) so umgesetzt worden. 

Also in der Hierarchie so: 
Person (foaf)
--> Ehemalige Mitarbeiter
--> Ehemalige Professoren

Passt das?

**Comment by dofeldsc** [comment]
Jo so war auch meine erste Idee, dann kann man später besser unterscheiden wer noch da ist und wer nicht. Ich baue die beiden Klassen dann in die UOS-Ontologie ein.

**Comment by dofeldsc** [comment]
Wie sollen die Klassen denn auf deutsch heißen? Mein Vorschlag wäre einfach
- former employees
- former professors
Oder was soll ich als englisches Label nehmen?

**Comment by dofeldsc** [comment]
Ich habe es mal zum Testen in "https://fis.virtuos.uni-osnabrueck.de/vivouos/" und ".../vivotest" eingebaut, du kannst ja mal schauen ob das so passt. 
Ich habe anstatt foaf:Person die kdsf:Person als Oberklasse genommen. Das sollte an sich keinen Unterschied machen aber ich denke wir orientieren uns ja eh mehr an den kdsf-Sachen.

Was mir aufgefallen ist:
- im Label wird eigentlich immer die Einzahl verwendet (rdf-local-name also in der URI die Mehrzahl)
- sollten wir bei neuen Labeln jetzt direkt die gendergerechte Schreibweise nutzen?

**Comment by dofeldsc** [comment]
Wie gerade besprochen:
-> Jetzt nur noch eine Klasse mit den Labels:
- ehemalige Beschäftigte
- former employees
