### ISSUE TITLE
css style links am corporate design der uni orientieren

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#41]
bitte den style für die links entsprechend der uni seite (corporate design) übernehmen. 

bsp: 
https://fis.virtuos.uni-osnabrueck.de/vivouos/leitlinien
dort fallen die links zu den externen seiten kaum auf. 

oder lieber #2 wieder eröffnen?

**Comment by sonschul** [comment]
hier noch mal der vergleichslink auf den uni-seiten:
https://www.uni-osnabrueck.de/universitaet/zahlendatenfakten/transparenz_der_forschungforschungsethik.html

**Comment by dofeldsc** [comment]
als info, ich habe das css dafür letzte Woche schon eingebaut  (https://github.com/FISvirtUOS/VIVO/blob/theme-uos/webapp/src/main/webapp/themes/tenderfoot_uos/css/tenderfoot.css).
Man kann also einfach die Klasse "uos_style" benutzen.

**Comment by sonschul** [comment]
muss ich mich darum im html code (leitlinien) schon kümmern oder macht @manschwa das?

**Comment by dofeldsc** [comment]
Ich habe den Text mit gewünschtem Style in die Quelldateien übernommen aber dabei ist mir aufgefallen das ein paar Links ins nichts führen.

- Etablierung eines Forschungsinformationssystems 
- Wissensforum
- Universitätsreden

Sind das Seiten die noch in Vivo angelegt werden sollten?

**Comment by sonschul** [comment]
Waren das nicht Links, die auf die Uni-Seite (extern) verlinken und nicht auf das VIVO ?

**Comment by dofeldsc** [comment]
<a href="/veranstaltungen/zentrale_veranstaltungen/osnabruecker_universitaetsreden.html" target="de/presse_oeffentlichkeit/veranstaltungen/osnabruecker_">Universitätsreden</a>

Das weiß bzw wusste ich nicht aber die Links funktionieren so auf jeden Fall nicht. 
Ich habe die jetzt mal angepasst aber noch nicht auf dem Server neu gebaut, also nicht wundern
