### ISSUE TITLE
Mittelgeber-Seite (z.B. DFG)  leer / Ohne zugeordnete Projekte

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#42]
Kann bei gelegenheit noch jemand schauen, warum die seite der mittelgeber keine liste der zugeordneten projekte enthält? 
siehe: 
https://fis.uni-osnabrueck.de/vivouos/individual?uri=http%3A%2F%2Flod.tib.eu%2Fonto%2Fkdsf%2FDFG

falls fehler schon bekannt ist, dann bitte löschen!

**Comment by sonschul** [comment]
dieses projekt sollte beispielweise auftauchen: 
https://fis.uni-osnabrueck.de/vivouos/display/project73c95c9d31951eaf52496aeaa47acf53

**Comment by dofeldsc** [comment]
Der "Fehler" war das die Property "hatMittelgeber" nicht als symmetrisch eingetragen war, also immer nur in eine Richtung sichtbar war.

Ich ändere das dann in der KDSF-Ontologie und das kommt mit dem nächsten Update in System. (in fis.uos.de/vivouos) habe ich es gerade aus Testzwecken schon in der Oberfläche gemacht.
