### ISSUE TITLE
hinweistext im koautorInnen-netzwerk anpassen

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#44]
bitte in der gelben textbox den folgenden text streichen:

"Loggen Sie sich ein, um auf Ihrer Profilseite zusätzliche Angaben zu Ihren Publikationen zu machen."

**Comment by dofeldsc** [comment]
Es gab auch noch einen Text "Loggen Sie sich ein, um auf Ihrer Profilseite zusätzliche Angaben zu Ihren Forschungsprojekten zu machen.", die habe ich auch mal entfernt wenn das okay ist? Falls nicht, Ticket wieder öffnen und Bescheid geben.

Ich pushe das gleich aber auf den Servern baue ich das dann morgen mit den anderen Änderung ein.
