### ISSUE TITLE
feedbackForm anpassen

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#45]
So wie in dieser Vorlage nur ohne Ort und ohne Telefon hätte ich es gerne: 

![image](https://user-images.githubusercontent.com/40201793/51679232-a56b8a80-1fde-11e9-9210-73bf8f26ed44.png)

Quelle: [Link](https://www.kontaktformular.com/kontaktformular-mit-dsgvo-eu-datenschutz-grundverordnung-fuer-ihre-website.html)

**Comment by dofeldsc** [comment]
An sich fehlte beim Standardformular in Vivo nur der Betreff, den habe ich hinzugefügt. Passt dir das so oder wolltest du auch den Style angepasst haben?

**Comment by sonschul** [comment]
Bitte noch die folgenden Style / Content - Anpassungen: 
1.) Header statt "VIVO Feedback Form" in DE "Kontaktformular" und in EN "Feedback Form" 
(Anmerkung: VIVO soll möglichst nur noch im Logo stehen.) 
2.) Statt "Vollständiger Name" nur "Name" 
3.) Statt "E-Mail-Adresse" nur "E-Mail"
4.) Text im Button ändern von "Mail senden" zu "Senden" 
5.) Alle Textfelder gleich groß und etwas größer als im jetzigen Entwurf. (ähnlich wie oben)
6.) Hinweis auf die Datenschutzerklärung mit Link zur DE und der Checkbox. 

Optional: 
Bei dem Button "Löschen" bin ich mir noch unschlüssig, ob das notwendig ist...
