### ISSUE TITLE
menü skaliert nicht richtig 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#46]
![image](https://user-images.githubusercontent.com/40201793/51679949-a2719980-1fe0-11e9-9aa2-29a90e1b99fd.png)

sobald das menü auf den burger icon wechselt, ist die anzeige der menüpunkte nicht mehr optimal. 
(überlappung mit der suchleiste, volle breite, ...)

**Comment by dofeldsc** [comment]
Ist bei mir nicht so, in welchem Browser und in welchem Vivo-System machst du das denn?
Sowas am besten immer direkt mit angeben.

**Comment by sonschul** [comment]
https://fis.uni-osnabrueck.de/vivouos/
mit Google Chrome 
gerade noch mal getestet.
