### ISSUE TITLE
Auflistung von Projekten auf Fach-Seite 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#47]
Bitte schauen, ob es möglich ist, dass die Projekte der Fächer auch auf den Fach-Übersichtsseiten auftauchen: 

Beispiel Kognitionswissenschaft
https://fis.uni-osnabrueck.de/vivouos/display/field25

Hier müssten mehr Properties (Personen / Projekt - Zuordnung) aufgeführt werden. 

siehe Ticket #42

**Comment by dofeldsc** [comment]
Ich habe eine gute Lösung gefunden. Beim Fach würde ich dann für jede Klasse eine eigene property einrichten, welche die jeweiligen Verknüpfungen zu einer Klasse anzeigt. Zusätzlich muss es eine Property geben, welche alle Verbindungen von einem der vier Klasse zum Fach auflistet, die habe ich aber erst ab Admin freigeschaltet also sieht die niemand (kann man theoretisch auch ganz unsichtbar machen).

Dafür bräuchte ich jetzt die deutschen und englischen Labels, welche auf der Fach-Seite auftauchen sollen (gilt natürlich auch jeweils für die Unterklassen):
- Beschaeftigter: 
- Drittmittelprojekt:
- Publikation:
- StrukturiertesPromotionsprogramm:
- "hatFachinv" (Die Property die nur der Admin sieht):
Man kann auch welche weglassen, wenn wir die nicht brauchen.

WICHTIG: Ich füge damit neue Faux-Properties für die KDSF-Ontologie hinzu, aber nur mit den englischen Labels, die deutschen werden über die Sprachdateien hinzugefügt (VIVO-languages/home/src/main/resources/rdf/display/everytime/PropertyConfig_de_DE.nt)

**Comment by sonschul** [comment]
Nur noch mal zur Sicherheit: 
Die Labels tauchen nur auf der Seite vom Fach auf, richtig?

**Comment by dofeldsc** [comment]
genau, ein Label für jede Klasse und ihre ganzen Unterklassen und eins für die Parent-Property, die aber nur Admins sehen.

**Comment by sonschul** [comment]
Sowas wie:
- Fachvertreter*in
- Fachbezogene Drittmittelprojekte
- Fachbezogene Publikationen
- Assoziierte Promotionsprogramme

**Comment by dofeldsc** [comment]
Dann noch die letzte also die die alles zusammenfasst
- "Fachzugehörigkeit?" sieht ja eh keiner

und dann noch die englischen Labels

**Comment by sonschul** [comment]
Ich fürchte, dass es keine so genauen Übersetzungen im Englischen für Fachvertreter und Fachzugehörigkeit gibt. 
Kannst du mir mal ein Screenshot von der jetztigen Ansicht aus deinem lokalen Testsystem schicken? 
Nur, damit ich mal sehe an welchen Stellen das auftaucht. 
Wenn das so verschachtelt ist wie bei der "offers" Ansicht, dann könnte man vielleicht auf erster Ebene 
"Field of Research" 
und darunter einfach mit "Person", "Publication", "Project" weitermachen. 
In den Beispielen der Dokumentation wurde auch für unterschiedliche faux properties die gleichen bezeichnungen verwendet. Müsste ich mal sehen wie es in der Oberfläche aussieht.

**Comment by dofeldsc** [comment]
![vivo_hatfach](https://user-images.githubusercontent.com/9248706/52112304-61900b00-2606-11e9-88e8-642e3bfd1e93.png)
Ne so nicht, sondern jede Klasse hat eine eigene Property

**Comment by sonschul** [comment]
Ok! 
Hat das Auswirkungen auf die Datenlieferungen? (Struktur der Excel-Tabellen, die wir liefern sollen)

**Comment by dofeldsc** [comment]
Nein, das ist ja das schöne an der Lösung :)
Ist das so denn gut?

**Comment by sonschul** [comment]
Wenn die Publikationen auch in dem Format angezeigt werden, dann ja! 

Noch ein Gedanke dazu, aber nur als Randbemerkung: 
Ich bin mir nicht sicher, ob durch das anbinden der Fächersystematik von DESTATIS mit der Lösung von tatiana (als kontrolliertes Vokabular) die Fachzurodnung nachher nicht doppelt ist. 
Vorteil deiner Lösung ist die Freiheit bei der Benennung der Fächer (uni-eigene Namen), bei DESTATIS wäre es die Standardisierung, die wir bei einem späteren Reporting nach KDSF brauchen. 
--> wir nehmen erstmal deine Lösung 👍

**Comment by dofeldsc** [comment]
"Meiner Lösung", das "hatFach" kommt aus der KDSF-Ontology und dazu habe ich eine Inverse Property hinzugepackt die einfach nur bei den unterschiedlichen Klassen anders aussieht. 
Wenn ihr die Standardnamen anliefert dann kann man die entweder zusätzlich hinterlegen oder auch direkt verwenden. 
Ich nehme jetzt als englische Labels einfach:
- Person
- field-related publications
- field-related projects
- associated doctoral programmes
- Field of Research
Damit ich das mal pushen kann.
