### ISSUE TITLE
template Personen Profil anpassen

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#49]
Solange noch nicht für alle Forscher Informationen zur Forschungsleistungen hinterlegt sind, sollen nur die Kontaktdaten in der grauen Box, nicht aber die Reiter "Affiliation", "Research", etc. sichtbar sein. 
(alles unter der grauen Box kann weg)

Bitte das Template so anpassen, dass folgende Informationen in der grau-hinterlegten Box erscheinen: 

[Titel] [Nachname] [Zusatz] , [Vorname]
[Bezeichnung der Professur] für [Denomination]
[Fachbereich]
[Institut]
[Fach]

Forschungsgebiete: [Schlagwörter] *mit Komma getrennt* 

[Briefumschlag-Logo] [E-Mailadresse]

**Comment by sonschul** [comment]
![nachher-profil](https://user-images.githubusercontent.com/40201793/53334947-7c4e5a80-38fa-11e9-993a-dde9a7774d03.png)

**Comment by sonschul** [comment]
Der Entwurf hat grundsätzlich Frau Menzels Zustimmung gefunden. 
Es soll jedoch noch ein weiteres Feld für die Angabe einer URL zu einem externen Profil ergänzt werden. 
Am besten unter der E-Mail, oder?

**Comment by dofeldsc** [comment]
"Forschungsgebiete" zu "Forschungsschwerpunkte" umbenennen (auch englisches Label über i18n hinzufügen)
Die zusätzlichen Mails (auch unter Kontaktinformationen) mit in den grauen Kasten. Rechts unter die Mail
