### ISSUE TITLE
Datenschutz / Copyright anzeige

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#5]
In der Datei footer.ftl des themes tenderfoot_uos (Vivo/webapp/themes/tenderfoot_uos/templates/page/partials) wird der Link für die Datenschutzerklärung / copyright Seite geswetzt. Man kann im "Site Admin" unter "Site Information" den Anzeigetext und die URL setzen. 
Dann hat man nur das Problem, dass die Mehrsprachigkeit an dieser Stelle kaputt geht. Der Titel des Links benutzt schon das i18n label "menu_copyright" aber der Anzeigetext nicht... Hier ist jetzt zu entscheiden was da in welchen Sprachen stehen soll. Dann passe ich ggf. das Template und die deutsche Sprachdatei (da heißt es nämlich auch "copyright" / VIVO-languages) an oder wir setzen einfach eine feste Bezeichnung

**Comment by dofeldsc** [comment]
Dazu passt eigentlich auch noch die Frage ob das Impressum nur in deutsch vorhanden sein soll oder auch in englisch? Sonst finde ich die Version im myShare gut. Ich gieße das dann mal in html und lade das wie die Datenschutzerklärung in das Doku-Repo. Das Impressum muss dann in die Datei  "aboutPage" (home/src/main/resources/rdf/display/firsttime), falls es die englsiche Version ist einfach in VIVO und bei allen anderen Sprachen dann im VIVO-language Repo.
-> Mal ausprobieren ob man die aboutPage nicht auch in englisch im language Repo hinterlegen kann/sollte?

**Comment by sonschul** [comment]
Sprechen wir an dieser Stelle vom MiniVIVO oder dem VIVO@UOS Produktivsystem?
Ich denke für das MiniVIVO würde das deutsche Impressum ausreichen, weil wir zur Umsetzung der Leitlinien keine Mehrsprachigkeit brauchen. 
Für das Produktivsystem würde ich beide Varianten einbauen. Soll ich die englische Version auch schon in den myShare Ordner legen?

**Comment by dofeldsc** [comment]
Ja gerne, dann baue ich das direkt für beide Sprachen ein.

**Comment by dofeldsc** [comment]
Hat keine Eile, erstmal nur in deutsch

**Comment by sonschul** [comment]
Von Björn gab es zum Impressum keine Einwände. Kann man das noch irgendwo als Link einbauen ?
Zur Datenschutzerklärung hat er mir nach den "Systemtest" keine Rückmeldung mehr gegeben. Habt ihr noch was gehört, ob er Stresstest durchgeführt hat?

**Comment by dofeldsc** [comment]
Er hat sich noch nicht gemeldet. Sollte das ein richtiger Stresstest sein wird er da auch Probleme kriegen da er nur die URL zu unserem "Testsystem" hat. Auf das Ergebnis bin ich mal gespannt.

Das Impressum kannst du gerne unter https://github.com/FISvirtUOS/VIVO-languages/blob/master-uos/home/src/main/resources/rdf/display/firsttime/aboutPage_de_DE.n3 einbauen. Ich muss schauen ob ich das dann bis morgen noch geladen bekomme.

Hier auch wieder gerne direkt in deutsch und englisch, entweder heute oder dann in der nächsten Zeit nachreichen.

**Comment by sonschul** [comment]
Die Inhalte des Impressums unter https://github.com/FISvirtUOS/VIVO-languages/blob/master-uos/home/src/main/resources/rdf/display/firsttime/aboutPage_de_DE.n3  sind soweit schon in Ordnung werden aber unter https://fis.uni-osnabrueck.de/vivouos/about nicht angezeigt. Hatte ich versucht am Montag schon im Slack zu beschreiben.

**Comment by dofeldsc** [comment]
Ja ich weiß und ich habe versucht zu beschreiben das solche Dinge nur geladen werden wenn man das System zum ersten Mal deployed. Es gibt zur Zeit keine gute Möglichkeit das nachzuladen.

Das Impressum im VIVO-languages Repo ist aber nicht das was du mal rumgeschickt hast.

**Comment by dofeldsc** [comment]
Ist beides in deutsch und englisch eingebaut. Die Symbole der Links habe ich auch eingefügt. Du kannst ja mal schauen ob das so passt und Bescheid sagen wenn du deine Änderungen vorgenommen hast.

Dann baue ich danach nochmal neu und dann sollte das passen.

**Comment by sonschul** [comment]
Hmmm... Hab den Cache geleert, aber sehe noch keine Symbole in der DE und dem Impressum... 
Bin ich auf der richtigen Maschine? virtuos / vivouos?

**Comment by sonschul** [comment]
Hat sich erledigt! Hab gesehen, dass du das jetzt schon aufs Live-System übertragen hast.
