### ISSUE TITLE
template Startseite ändern

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#50]
![image](https://user-images.githubusercontent.com/40201793/53394628-1d432100-39a0-11e9-9d02-6177a14a2dff.png)

Subtickets:
- [x] https://github.com/FISvirtUOS/uos_fis_doku/issues/2
- [x] https://github.com/FISvirtUOS/uos_fis_doku/issues/3

**Comment by sonschul** [comment]
Wo war eigentlich noch gleich das Kontaktformular verlinkt?

**Comment by sonschul** [comment]
Layout in der oben stehenden Form findet Zustimmung und kann so umgesetzt werden.

**Comment by dofeldsc** [comment]
Gibt es den Text in der grauen Box eigentlich schon irgendwo?

**Comment by sonschul** [comment]
So wie im Screenshot, der Inhalt liegt im Textformat vor, kann ich dir morgen per Mail/Slack schicken. 
Leider funktioniert der Zugriff von zu Hause gerade nicht...

**Comment by dofeldsc** [comment]
Danke. 
Die 6 Profillinien auf der Startseite sollen auch entfernt werden?

**Comment by sonschul** [comment]
Ja, genau. Die sollen vorläufig raus, weil nicht genug Inhalt eingepflegt ist.

**Comment by sonschul** [comment]
Anbei der Text für die Startseite:

„Über diese Seiten erhalten Sie in Umsetzung der landesseitigen Leitlinien „Transparenz in der Forschung“ wesentliche  Informationen über jeweils  zum 1.12. eines Jahres - 2015 beginnend  - drittmittelgeförderte Forschungsprojekte an der Universität Osnabrück. 

Ihre Recherche wird auf der einen Seite durch die ausgewiesene Auflistung der Drittmittelprojekte  bzw. Projektergebnisse unterstützt. Auf der anderen Seite können Sie aber auch gezielt nach Drittmittelprojekten, -inhalten und -ergebnissen oder nach Personen oder Einrichtungen wie u.a. nach Fachbereichen, Instituten oder Seminaren suchen.“

**Comment by dofeldsc** [comment]
Als englischen Text habe ich jetzt erst einmal die Ausgabe der DeepL-API genommen: 
"On these pages, you will find essential information on research projects at the University of Osnabrück funded by third parties, each starting on 1 December of a year - 2015 - in implementation of the regional guidelines „Transparency in Research.

Your research is supported on the one hand by the list of third-party funded projects and project results. On the other hand, you can also search specifically for third-party funded projects, contents and results or for persons or institutions such as departments, institutes or seminars."

In unserem System kann man anfangs eh nicht umschalten aber dann ist wenigstens ein ungefähr passender Text vorhanden. 


Die Umsetzung der drei Übersichten (Subticket https://github.com/FISvirtUOS/uos_fis_doku/issues/2) müsste man noch etwas schöner machen und genau sagen was gewollt ist. 
- In dem Bild hier steht Projektverantwortliche, im anderen Ticket steht nichts dazu
- Forschungsprojekte steht im Subticket, hier Drittmittelprojekte
- Forschungsergebnisse: Sind bei uns nur Publikationen bis jetzt

**Comment by dofeldsc** [comment]
Der Titel passt noch nicht

**Comment by dofeldsc** [comment]
Alles erledigt, wird aktualisiert sobald ich nächste Woche (KW 19) die neue Instanz aufsetze

**Comment by sonschul** [comment]
Zeilenabstände etwas vergrößern auf 
line-height: 1.5em; 

im `<div class="intro_text uos_style">` 
und `<div class="jumbotron uos-jumbotron">`

wenn ich es im `.jumbotron p` über F12 teste, wird es in beiden Absätzen geändert. 
also kurz: den beiden Begrüßungstexten auf der Startseite.
