### ISSUE TITLE
Anzeige der AutorInnen im Drittmittelprojekt

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#52]
Es soll eine Möglichkeit gefunden werden die nicht zur Uni gehörenden "externen" AutorInnen von Publikationen oder generell Projektergebnissen darzustellen. 

Zwei Möglichkeiten wären:
- Das Template für die Anzeige dieser Personengruppe in ähnlicher Weise zu der öffentlichen Ansicht von Professoren abzuändern. Dann würde nur der Name und ggf. ein Foto oder ähnliches angezeigt
- - Das würde einem die Möglichkeit offen halten zusätzliche Informationen einzupflegen und diese auch anzuzeigen.
- Die zweite Möglichkeit wäre die Links zu diesen Personen (im Projektergebnis) zu deaktivieren. Man bekommt die Information über den Namen aber kommt nicht auf dessen Profil. Zusätzlich müsste man die Klasse aus der globalen Suche ausschließen. 

Die erste Lösung geht wahrscheinlich schneller aber man hätte viele "leere" sichtbare Profilseiten. Man muss auch erstmal schauen ob sich die Änderungen für die zweite Möglichkeit überhaupt gut umsetzen lassen.

**Comment by sonschul** [comment]
Hier ein Beispiel von der TIB:
https://vivo.tib.eu/fis/individual?uri=https%3A%2F%2Fdoi.org%2F10.1007%2F978-3-319-56608-5_15

Dort ist die Person "Phan-Vogtmann, Lo An" nicht verlinkt zu einem Profil, aber über die globale Suche trotzdem aufzufinden. So fände ich das auch am besten. Falls das für das erste Release zu viel Aufwand ist, kann ich auch mit größtenteils leeren Profilen leben.

**Comment by dofeldsc** [comment]
Ja so hätte ich das auch gemacht aber wenn die das schon haben, kann man ja gucken ob wir das verwenden können :+1:

**Comment by dofeldsc** [comment]
Das gewünschte Verhalten lässt sich dadurch abbilden, dass man die gewünschten Personen nur als "Identity VCard" mit einer VCard "Name" initialisiert. 
Dafür müssen die Modelle der folgenden Listen angepasst werden:

- [ ] Co-Autoren -> Spalte "Wissenschaftliches-kuenstlerischesPersonalURI/Klasse" wird in dem Fall mit "Person" belegt sein
- [ ] Publikation_Person -> neue Spalte, in der steht "in Personendaten vorhanden" wenn diese Person schon existiert und sonst sollen auch nur die Namen über ein VCard eingebunden werden
- [ ] Projekte -> "Forscherrolle"?
- [ ] Projekt_MitarbeiterInnen -> "Forscherrolle"?

Gibt es sonst noch Tabellen oder Fälle wo dieser Fall beachtet werden muss?

**Comment by dofeldsc** [comment]
getestet und so in den aktuellen Karmamodellen mit Hilfe von Sonja umgesetzt
