### ISSUE TITLE
Datentyp Bewilliungssumme ändern für Auswertungszwecke  

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#53]
Für Auswertungszwecke (mit SPARQL) eignet sich der Datentyp "string" nur bedingt, war jedoch bislang erforderlich, weil für die Darstellung der Bewilligungssumme ein € - Zeichen gewünscht ist. 
Es soll ein alternativer Lösungsweg gesucht werden, der Zahl + € - Zeichen kombiniert.

**Comment by dofeldsc** [comment]
Eine "hässliche" Lösung wäre die SPARQL-Abfrage mit einer Konvertierung der Bewilligungssumme:
SELECT  (SUM(xsd:decimal(?summenclean)) AS ?DFGSumme)
WHERE {?project a kdsf:Drittmittelprojekt .
            ?project kdsf:hatMittelgeber ?mittelgeber .
            ?project kdsf:Bewilligungssumme ?bewillsumme .
         BIND((REPLACE(?bewillsumme, " € ", "")) as ?summe) .
 BIND((REPLACE(?summe, " ", "")) as ?summen) .
 BIND((REPLACE(?summen, ",00", "")) as ?summenclean) .
FILTER ( ?mittelgeber = <http://lod.tib.eu/onto/kdsf/DFG>)
}

Geplant ist den Datentyp der Property zu ändern und dann über eine eigene short-view das Eurozeichen anzuhängen. Vorher teste ich das aber mal so mit dem Datentyp der Property.

**Comment by sonschul** [comment]
Vielleicht sollten wir die SPARQL Abfragen schon mal irgendwo sammeln. 
Hab noch ne Kleinigkeit im SELECT-Teil geändert.

**Comment by dofeldsc** [comment]
Das bleibt erst einmal so. 
Man könnte den Typ zu float oder Int ändern aber dann wären in Vivo keine Trennzeichen erlaubt. Wenn man die nicht über die ABfrage filtern will dann musste man sie in der Anzeige hinzufügen. Dafür müssten auch die Listen angepasst werden und das Karmamodell geändert werden.

Kann man machen falls es mal notwendig werden sollte, aber auch nur da. (so mit Projektteam abgesprochen, 1.04.19)
