### ISSUE TITLE
Filtermöglichkeiten in Suchergebnis-Ansicht

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#54]
Als Einschränkung der Suchergebnisse in der rechten Box sollte andere Filtermöglichkeiten angezeigt werden: 
Bei "Forschung" sind "Publikationen" gemeint
Bei "Aktivitäten" sind  "Projekte" gemeint

Wenn dann ein Filter angewandt wird, erscheinen Klassen (aus den unterschiedlichen Ontologien vivo / kdsf ) wieder doppelt z.B. bei Publikationsart: "Artikel" oder "Person". 

In der Box sollte der Text zudem geändert werden auf "Beschränken der Ergebnisse auf" 
Nicht "Beschränken von [Klasse] bis".

![image](https://user-images.githubusercontent.com/40201793/57518729-fac37180-7319-11e9-8013-33a6c9bd78ff.png)

**Comment by sonschul** [comment]
![image](https://user-images.githubusercontent.com/40201793/57519513-c355c480-731b-11e9-9987-b37ff0972268.png)

Unklar, wann Inhalte der Seite als "Untertitel" in grau unter dem Publikationstitel angezeigt werden, und wann nicht...

**Comment by dofeldsc** [comment]
- Den Text ändere ich bei Gelegenheit
- Wollen wir die Klassengruppen ändern? Dann sollten wir mal schauen welche Klassen da für uns in Frage kommen
- Bei doppelten Klassen kdsf <-> vivo muss ich mal reinschauen, ich fürchte die müsste man Stück für Stück entfernen (das sollte aber durch die geplanten Änderungen von Tatiana im KDSF erledigt werden)

**Comment by sonschul** [comment]
> * Den Text ändere ich bei Gelegenheit
> * Wollen wir die Klassengruppen ändern? Dann sollten wir mal schauen welche Klassen da für uns in Frage kommen
> * Bei doppelten Klassen kdsf <-> vivo muss ich mal reinschauen, ich fürchte die müsste man Stück für Stück entfernen (das sollte aber durch die geplanten Änderungen von Tatiana im KDSF erledigt werden)

Wirkt sich die Bezeichnung der Klassengruppen denn tatsächlich nur auf die Such-Ergebnis-Filter aus? 
Oder wird das sonst noch irgendwo verwendet? 
Wenn es tatsächlich nur Einfluss auf die Suche hat, dann würde ich die Bezeichnung wie oben vorgeschlagen ändern wollen.

**Comment by dofeldsc** [comment]
Den Anzeigetext und die Klassengruppen habe ich geändert.

Zu dem Problem mit der unnötigen Klassenfilter gibt es mehrere Lösungsmöglichkeiten aber keine ist so richtig gut. Ich kann die hart entfernen aber ob man das möchte ist die Frage. Ich hab jetzt erst einmal die doppelten gefiltert.
Über den Rest können wir die Tage ja mal sprechen.

Für Mich noch als Notiz:
Vitro/webapp/src/main/webapp/templates/freemarker/body/search/search-pagedResults.ftl - Template
Vitro/api/src/main/java/edu/cornell/mannlib/vitro/webapp/search/controller/PagedSearchController.java - Controller

**Comment by sonschul** [comment]
![image](https://user-images.githubusercontent.com/40201793/58034703-7b0e8180-7b27-11e9-88c0-83480ce95ed8.png)

An der Stelle möglichst nur "Drittmittelprojekt".

**Comment by dofeldsc** [comment]
Ist erledigt, ich habe jetzt einfach eine Abfrage eingebaut die unerwünschte Werte filtert. Falls noch andere Einträge auftauchen  die entfernt werden sollen eben Bescheid geben.
In diesem Commit sieht man wo man die eintragen kann: 
https://github.com/FISvirtUOS/Vitro/commit/88805efc213236f26aa7af311c5a013f2834b62d 

Zusätzlich habe ich die Maße etwas erweitert so dass jetzt alle Werte passen sollten. Wenn wir jetzt anfangen da noch andere/längere Werte einzutragen müsste ich mir das nochmal anschauen.
So richtig gut geht das an der Stelle nicht ohne das Element komplett umzubauen.

**Comment by sonschul** [comment]
![image](https://user-images.githubusercontent.com/40201793/58169611-78c83680-7c91-11e9-8a68-7afa5ad0e0f2.png)

Für die Filtermöglichkeit auf 1. Ebene "Organisationen" sollte auf 2. Ebene die Klasse "Abteilung" und "Organisation" raus und in den Suchergebnissen steht auch immer noch das englische Label - "Academic Department" drin.

**Comment by dofeldsc** [comment]
Das Ticket ist erledigt und für die verbleibenden englischen Labels (initialTBoxAnnotations.n3) mache ich ein extra Ticket auf
