### ISSUE TITLE
Shortview projects mit Jahr und TeilnehmerIn

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#55]
Um gleichnamige Projekttitel differenzieren zu können, soll in der Shortview der Projekte zusätzlich das Jahr (Startjahr und ggf. Endjahr) + TeilnehmerIn unter dem Projekttitel erscheinen. 

![image](https://user-images.githubusercontent.com/40201793/57619946-9dccf300-7587-11e9-91d9-f421cf84ae91.png)
Bsp. vom Forschungskompass

**Comment by dofeldsc** [comment]
Ist drin und wurde für gut befunden. Falls da noch Anpassungen gewünscht sind einfach das Ticket öffnen und reinschreiben.
