### ISSUE TITLE
Reihenfolge der Properties auf der Projektseite 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#56]
Beschreibung
TeilnehmerIn
Organisationseinheit
Fach
Datum/Uhrzeit-Intervall
Mittelgeber
Bewilligungssumme
Ergebniszusammenfassung
Externe Projektseite

**Comment by dofeldsc** [comment]
Beschreibung - vivo:description (1) 
TeilnehmerIn - faux property of obo:BFO_0000055 (17)
Organisationseinheit - kdsf:hatOrganisationseinheit (-1) => (19)
Verbund/Partnerorganisation . uoscore:hatpartnerorganisation (-1) => (20)
Fach - kdsf:hatFach (-1)  => (21)
Datum/Uhrzeit-Intervall (Jetzt Projektlaufzeit) - vivo:dateTimeInterval (9)
Mittelgeber - kdsf:hatMittelgeber (-1) => (25)
Bewilligungssumme - kdsf:Bewilligungssumme (-1) => (27)
Ergebniszusammenfassung - uoscore:ergebniszusammenfassung (-1) => (29)
Externe Projektseite - uoscore:hatexterneprojektseite (-1) => (31)

Leider gilt das nur innerhalb der PropertyGroup also wird die Reihenfolge nicht vollständig passen

**Comment by dofeldsc** [comment]
Ist nicht perfekt aber fürs erste ausreichend, falls es notwendig werden sollte das weiter zu verfeinern nochmal das Ticket öffnen und dann schaue ich ob man das noch besser hinbekommt.
Die einzeln Gruppen werden halt nach und anch geladen und können nur innerhalb der Gruppe sortiert werden
