### ISSUE TITLE
Profilseiten für nicht Professoren

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#58]
Ich habe jetzt erst die Profilseite der Professoren auch bei den Wissenschaftlichen Mitarbeitern und so eingesetzt aber das passt nicht wirklich.

Muss ich noch anpassen bzw. ein eigenes erstellen.

**Comment by sonschul** [comment]
Leider werden die Mitarbeiter gar nicht mehr in der Suche angezeigt:
![image](https://user-images.githubusercontent.com/40201793/57831823-760fa200-77b6-11e9-9aa6-776878249540.png)
Auch wenn man einen Filter auswählt in dem eigentlich Instanzen vorhanden sein sollten, wird nichts mehr angezeigt:
![image](https://user-images.githubusercontent.com/40201793/57831844-84f65480-77b6-11e9-8c8d-63cd56a6aec2.png)

**Comment by dofeldsc** [comment]
Hat sich erledigt also der Kommentar.

Die enthaltenen Klassen:
Person - Haben keine Profilseite, nur VCard (nicht sichtbar)
Professoren - Eigenes Template für Professoren
Verwaltungspersonal - (bis jetzt noch Professoren-Template)
EhemaligeBeschaeftigte - (bis jetzt noch Professoren-Template)
WissenschaftlicheUndKuenstlerischeMitarbeiter - (bis jetzt noch Professoren-Template)

**Comment by dofeldsc** [comment]
Das bleibt erst einmal so, bei Bedarf ein MockUp machen und dann sprechen wir drüber
