### ISSUE TITLE
Überarbeitung Startseite

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#59]
Die Startseite soll etwas abgeändert werden:
- Änderung des Textes
- zum Teil Neuplatzierung des Textes
- Link einbauen zur "Leitlinien"-Seite

**Comment by dofeldsc** [comment]
![neue_frontpage](https://user-images.githubusercontent.com/9248706/57859376-17b4e480-77f3-11e9-8087-b6580d5069ed.png) 

![new_frontpage2](https://user-images.githubusercontent.com/9248706/57859375-17b4e480-77f3-11e9-8b06-df07f53f9786.png)

Also mir persönlich gefällt die zweite Version besser.

**Comment by sonschul** [comment]
Ich bin auf jeden Fall auch für die zweite Version!

**Comment by sonschul** [comment]
Weiter unten bei der Zufallsauswahl soll der mittlere Block "Projekte" heißen.

**Comment by sonschul** [comment]
@dofeldsc 

Kannst du dir den Absatz noch mal anschauen? 
Der Strich ist irgendwie verrutscht. Der gelbe Balken müsste komplett vor dem Absatz stehen so wie oben im Entwurf. 

![image](https://user-images.githubusercontent.com/40201793/58008155-15e96a80-7aec-11e9-8bb5-60887416711d.png)

**Comment by dofeldsc** [comment]
![frontpage](https://user-images.githubusercontent.com/9248706/58009456-ca848b80-7aee-11e9-9473-a2107a6cf287.png)

Bei mir nicht, magst du mal bitte die Seite hart neuladen wie ich dir das gezeigt habe? Sonst einfach mal im inkognito modus starten. Da ist der Cache ausgestellt

**Comment by sonschul** [comment]
![image](https://user-images.githubusercontent.com/40201793/58231480-67396a00-7d37-11e9-95ee-634849c57adc.png)

Könnten die beiden Überschriften Forschung und Projektergebnis umbenannt werden in "Projekte" und "Projektveröffentlichungen" ?
