### ISSUE TITLE
Footer "Hilfe" ersetzen durch "Über VIVO@UOS"

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#6]
Bitte im footer den link von Hilfe (duraspace) ersetzen durch eine "Über VIVO@UOS" - Seite. 
Dort soll kurz vorgestellt werden, welche Daten das VIVO@UOS abbildet und wie das VIVO im Gesamtprojekt FIS einzuordnen ist.

**Comment by dofeldsc** [comment]
Kann ich bei Gelegenheit mal machen. Gibt es den Text denn schon irgendwo?
