### ISSUE TITLE
Anpassungen im template Projekte 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#60]
![image](https://user-images.githubusercontent.com/40201793/57869674-d417a600-7805-11e9-8ae3-2dd4a9f15e89.png)

Kann das Klassen-Label in die nächste Zeile geschoben werden?

**Comment by dofeldsc** [comment]
Ist erledigt. Betraf nur Dateien in Vitro deswegen hier kein Link zum Commit
