### ISSUE TITLE
Shortviews Publikationen mit Autoren und Jahr

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#61]
![image](https://user-images.githubusercontent.com/40201793/57869967-746dca80-7806-11e9-9ea2-bb5f3b5ac62a.png)

Ähnlich wie bei #55 sollen die Autoren und das Veröffentlichungsjahr in der Liste angezeigt werden. 

Auf der Seite "Forschungsergebnisse" soll zudem nur die Klasse Publikation (nicht alle subclasses) angezeigt werden.

**Comment by dofeldsc** [comment]
[Klassen] [Jahr]
[Autoren]

**Comment by dofeldsc** [comment]
Ich habe es jetzt mal so umgesetzt, ohne Trennzeichen sah das irgendwie doof aus:
[Klasse] - [Jahr]
[Autor1]; [Autor2] usw.
![browse_publications](https://user-images.githubusercontent.com/9248706/58024364-4ba14a00-7b12-11e9-99bc-78e27b572644.png)

Die VCard Autoren werden auch nicht als Link angezeigt.
Passt das so?

**Comment by dofeldsc** [comment]
Ist drin und wurde für gut befunden. Bei Änderungswünschen am besten das Ticket wieder öffnen
