### ISSUE TITLE
<title> Seite Datenschutzerklärung ändern

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#63]
https://fis.uni-osnabrueck.de/vivouos/privacypolicy#

![image](https://user-images.githubusercontent.com/40201793/58004679-18e05d00-7ae4-11e9-9230-ffcc7943e7da.png)

Bitte deutschsprachig anzeigen "Datenschutzerklärung"

**Comment by dofeldsc** [comment]
gilt für mehrere Seiten:
- /imprint
- /aboutPage
- /privacypolicy
- /siteAdmin
- /revisionInfo

Muss man im entsprechenden Controller die getTitle Methode auf i18n umstellen

**Comment by dofeldsc** [comment]
Alle geändert, bei 4 im Controller und bei der AboutPage im Template einen deutschen Titel hinzugefügt. (alles in Vitro)
