### ISSUE TITLE
beim erstaufruf einer projektseite werden wenige property angezeigt (nicht alles anzeigen)

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#64]
![image](https://user-images.githubusercontent.com/40201793/58027877-ddf91c00-7b19-11e9-99e9-81613390a8be.png)

**Comment by dofeldsc** [comment]
Das Problem ist gelöst und kam daher das ich die anderen Tabs entfernt habe. Es gibt eine Java Script Datei die immer auf den Templates geladen wird. Da habe ich einfach die Methode ViewAll() beim initialen Ladevorgang hinzugefügt
