### ISSUE TITLE
index of contents 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#65]
Ich bin mir nicht sicher, ob wir schon vereinbart haben, dass der link zum "index of contents" sichtbar bleibt oder komplett rausgenommen wird. 
Wenn die Seite stehen bleiben soll, müssten die doppelten Einträge noch raus: 

![image](https://user-images.githubusercontent.com/40201793/58109718-69dc7800-7bee-11e9-924e-126fc8e7e61e.png)

**Comment by dofeldsc** [comment]
Ich habe den Link einfach mal entfernt, die Seite an sich gibt es aber noch.
