### ISSUE TITLE
anpassungen im template projects / reserachresults 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#66]
![image](https://user-images.githubusercontent.com/40201793/58156691-f6cb1400-7c76-11e9-8d2c-5b2cef5f3664.png)

`<h3 class="selected-class">...</h3>` kann entfernt werden.

**Comment by dofeldsc** [comment]
Ich kann das für alle Menü- bzw. Übersichtsseiten entfernen aber nur sehr unschön für diese eine.
Soll das dann auch auf der Personenseite, etc entfernt werden? Man hat ja links eh die ausgewählte Klasse. 
Falls es bei allen entfernt werden soll:
h3 entfernen - Vitro/webapp/src/main/webapp/templates/freemarker/body/partials/menupage/menupage-browse.ftl
JS entfernen - Vitro/webapp/src/main/webapp/js/menupage/browseByVClass.js

**Comment by sonschul** [comment]
Aus meiner Sicht ist die Information redundant und kann auf allen Menü/Übersichtsseiten entfernt werden.
