### ISSUE TITLE
Profilseite der Professoren

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#7]
Nicht alle Abschnitte (Affiliation, Research, Contact aber "Alle anzeigen") werden übersetzt.

![grafik](https://user-images.githubusercontent.com/40201793/48077384-829fb600-e1e7-11e8-9639-87fbae82570f.png)

**Comment by manschwa** [comment]
VIVO/webapp/src/main/webapp/themes/tenderfoot/templates/body/partials/individual/individual-property-group-tabs.ftl:24

**Comment by dofeldsc** [comment]
Da wir jetzt erst einmal mit der "nicht angemeldeten Ansicht" arbeiten hat sich dieses Ticket erledigt.

Über Anpassungen an dieser Sicht kann man dann später wieder nachdenken.
