### ISSUE TITLE
Link in Projektergebniszusammenfassung nicht anklickbar

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#73]
Eventuell korrespondiert das zu #31 

Beispiel für nicht funktionierenden Link: 
https://fis.uni-osnabrueck.de/vivouos/display/project82cd93254d6a777151d54591c062f6bb

**Comment by dofeldsc** [comment]
Das hat leider nichts mit dem Ticket #31 zu tun. 
Man kann nicht einfach in ein Textfeld (Ergebniszusammenfassung ist als Text-Property definiert) einen Link schreiben und der wird dann automatisch anklickbar.

Wenn das gewünscht ist muss ich mal schauen ob man das anpassen kann aber das ist so in VIVO bis jetzt noch nicht vorgesehen aber kann man bestimmt irgendwie bauen.

**Comment by dofeldsc** [comment]
https://fis.uos.de/vivouos/display/project8d49f9bdb90a6923700f006a884ab386

Hier ist ein Beispiel wo der Link abgeschnitten wird und somit nur auf die Startseite der Homepage verlinkt.
Muss ich mir nochmal anschauen
