### ISSUE TITLE
Label "Mittelgeber" ändern 

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#75]
Das Label der Property vom Mittelgeber zu den Projekten soll von "Mittelgeber" auf "Vom Mittelgeber finanzierte Projekte" geändert werden!

**Comment by dofeldsc** [comment]
Als englische Bezeichnung habe ich erst einmal "Projects financed by the donor" mit eingebaut

**Comment by sonschul** [comment]
> Das Label der Property vom Mittelgeber zu den Projekten soll von "Mittelgeber" auf "Vom Mittelgeber finanzierte Projekte" geändert werden!

Ist es möglich das Label der Property (kdsf:hatMittelgeber) von Projekt zu Mittelgeber (also genau umgekehrt) auf "Finanzierung durch" zu ändern? 

Es ist auf den Projektseiten aufgefallen, dass es dort nicht ganz stimmig ist:

![image](https://user-images.githubusercontent.com/40201793/70638126-9e6e5a80-1c38-11ea-8718-739cb6f35f11.png)

**Comment by sonschul** [comment]
Englische Bezeichnung: "Financing"

**Comment by dofeldsc** [comment]
ist erledigt, die Tage dann nochmal auf dem Testserver testen
