### ISSUE TITLE
Projektlaufzeit zu den Projekttitel einfügen

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#76]
![image](https://user-images.githubusercontent.com/40201793/59680424-95448980-91d1-11e9-933c-0ba944e6bfc0.png)
Auf den Fach-Seiten die Projektlaufzeit zu den Projekttitel einfügen, um Projekte besser differenzieren zu können.

**Comment by dofeldsc** [comment]
Ich habe das jetzt bei mir mal lokal eingebaut.
Wie soll das denn genau aussehen, einfach nur das Datum bzw. das Intervall dahinter mit Leerzeichen getrennt oder wie?
Soll das dann auch anklickbar sein so das man darüber auch zum Projekt kommt?

**Comment by dofeldsc** [comment]
![Bildschirmfoto vom 2019-06-28 15-48-23](https://user-images.githubusercontent.com/9248706/60346795-372b5980-99bc-11e9-840f-c8d4c4695a41.png)
Ich würde sowas bevorzugen, Intervall in Klammern und nicht teil des Links also daher etwas grauer

**Comment by sonschul** [comment]
Die Umsetzung finde ich sehr gut. (nicht Teil des Links und leicht ausgegraut)
