### ISSUE TITLE
Template Projekt-Detailseite

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#78]
![Projekt-Detailseite](https://user-images.githubusercontent.com/40201793/59828769-0738e200-933c-11e9-927f-1753b527b57a.png)

**Comment by sonschul** [comment]
Reihenfolge der Properties unter Header (Projekttitel): 
1.  Beschreibung:
2.  Projektleitung:
3.  Projektlaufzeit:
4.  Bewilligungssumme: 
5.  Verbund-/Partnerorganisationen: 
6.  Drittmittelgeber nach KDSF: 
7.  Förderkennzeichen des Mittelgebers: 
8.  Schlagwörter: 
9.  Übergeordnetes Projekt von: 
10. Teilprojekt von: 
11.  Ergebniszusammenfassung:

**Comment by dofeldsc** [comment]
Wollen wir da noch mit K&M und so drüber diskutieren oder soll ich schon anfangen das umzusetzen?

**Comment by sonschul** [comment]
Du kannst ruhig einen Entwurf fertig machen.

**Comment by dofeldsc** [comment]
Wir verwenden für die Icons unten welche von der Seite https://fontawesome.com/icons, dazu müssen wir einen Link in die Terms of Use aufnehmen! 

Zitat:
"This SVG Icon Requires Attribution
Before you download, this icon is licensed under the Creative Commons Attribution 4.0 International license and requires that you comply with the following:

You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

If this is a real thorn in your side, grabbing a paid plan removes this attribution restriction (and gives you tons more icons and goodies too)."

**Comment by sonschul** [comment]
Kleine Layout-Änderungsvorschläge

Im Header:
- gelber Balken etwas schmaler
- Abstände zwischen den Zeilen größer
- (Projekttitel) Überschrift größer 
- FB und Fach besser unten mit aufführen

Im beschreibenden Text:
- Projektlink-URL durch Kurztexte ersetzen z.B. ("Link")

**Comment by sonschul** [comment]
![image](https://user-images.githubusercontent.com/40201793/61710554-2c14e080-ad52-11e9-8ccf-962234307de7.png)

Projektstatus in nächste Zeile
