### ISSUE TITLE
template Suchergebnis-Seite

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#8]
Auf der Seite der Suchergebnisse sollte in der Box "Zeige nur" die deutsche Klassenbezeichnung stehen. 

![grafik](https://user-images.githubusercontent.com/40201793/48183308-9570d280-e32e-11e8-9118-dfa5efc7492a.png)

**Comment by manschwa** [comment]
Vitro/webapp/src/main/webapp/templates/freemarker/body/search/search-pagedResults.ftl:36

**Comment by sonschul** [comment]
Falls sich die deutschen Übersetzungen nicht einblenden lassen, bitte die "Zeige nur" Box entfernen. 

Unter der dem searchResultsHeader bitte den Infotext hinzufügen: 
"Derzeit werden nur Inhalte angezeigt, die im Rahmen der [Leitlinien zur Transparenz in der Forschung] veröffentlicht werden sollen."  und auf die Seite der Leitlinien verlinken: siehe #35

**Comment by dofeldsc** [comment]
Habs gefixt (https://github.com/FISvirtUOS/Vitro/commit/a95a4ab05f4861ef26d8e7d7cfbc55722703a2a1) aber mal schauen was die Community dazu sagt. Habe das mal im i18n Channel angesprochen aber noch keine Rückmeldung bekommen.
Vielleicht haben die auch eine bessere Idee

**Comment by dofeldsc** [comment]
Ich habe keine Rückmeldung mehr bekommen also lass ich das jetzt einfach so. Falls die sich bei irgendwem melden, der Commit ist ja oben verlinkt.
