### ISSUE TITLE
Druckansicht / URI ausblenden

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#80]
Bei Gelegenheit könnte die Druckansicht optimiert werden. 
Derzeit werden die URI mit eingeblendet. (siehe Screenshot). 

![image](https://user-images.githubusercontent.com/40201793/59855021-61559980-9374-11e9-9c2a-8c867eca61ab.png)

**Comment by dofeldsc** [comment]
UOS Logo ist in der Druckansicht etwas abgeschnitten, eigentlich nicht schlimm aber vllt mal anschauen

**Comment by dofeldsc** [comment]
wie gerade besprochen hat sich das erledigt
