### ISSUE TITLE
Status ( Laufend/ Abgeschlossen ) als Property bei Drittmittelprojekten hinzufügen

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#82]
Der Projektstatus soll als "Laufend" oder "Abgeschlossen" bei Drittmittelprojekten hinzugefügt werden.
 
Für spätere Facetten-Navigation / Filtermöglichkeiten in der Suche und auch jetzt schon in der Darstellung auf der Projektsuchseite unter https://fis.uni-osnabrueck.de/vivouos/projects und im überarbeiteten Template für die Projektdetailseite jeweils hinter der Laufzeit einblenden.

**Comment by dofeldsc** [comment]
Als Property bedeutet dann das ihr das über den Import einspielen wollt? 
Das können wir gerne machen aber das System wird nicht automatisch erkennen das die Laufzeit überschritten ist und dann die Property von Laufend auf Abgeschlossen ändern. Das wird dann immer nur bei einem Update der Daten passieren...
Das Datum was dort jetzt angezeigt wird, ist einfach das Label des Zeitintervalls. Wenn das eh nur beim Import geändert werden soll kann ich das gerne direkt ins Label des Intervalls aufnehmen. Dann steht das auch so auf der Seite des Drittmittelprojekts.

Was die Filtermöglichkeiten angeht, dafür brauch man das nicht oder willst du nach den Worten filtern? Da hatten wir eigentlich schon mal drüber gesprochen

**Comment by dofeldsc** [comment]
Ist im neuen Projekt-Template umgesetzt. Eine SPARQL holt das End-Datum und vergleicht das dynamisch mit dem aktuellen. Falls kein End-Datum angegeben ist wird automatisch angenommen das das Projekt noch läuft!
