### ISSUE TITLE
Neues Template für Beiträge des Wissensforums

### ISSUE THREAD

**Issue by dofeldsc** [FISvirtUOS/VIVO#85]
Wir wollen Facebook, Youtube, Instagram und vielleicht noch Twitter auf bestimmten VIVO-Seiten einbinden. 
Fürs erste beschränken wir uns auf die Seiten der Eventreihe "Osnabrücker Wissensforum".
Dazu zählen die Klassen:

Bei diesen Instanzen gibt es meist ein Foto, eine Beschreibung, einen Autor mit Kontaktdaten und ein Video des Vortrags. Für Testzwecke enthält die Seite abschließend auch einen eingebundenen Facebook- und Twitter-Feed. Diese sind so um Design noch nicht vorgesehen aber veranschaulichen die mögliche Einbettung.

Die Umsetzung geschieht zu Anfang auf dem Testsystem https://fis.virtuos.uni-osnabrueck.de/vivouos/ 
Für diesen Zweck wurde die Testinstanz einer Präsentation angelegt  (https://fis.virtuos.uni-osnabrueck.de/vivouos/display/n6238) mit der sich der initiale Entwurf besprechen lässt.

**Comment by dofeldsc** [comment]
Offene Fragen:
-  Soll es eine Instanz "X. Osnabrücker Wissensforum" geben in der alle zugehörigen Vorträge aufgelistet sind?
   - Wäre über Eventreihe möglich
- Warum gibt es ein Spalte "Fach" und "Fach_Bez" wo die "Fach_Bez" nicht auf das ausgewählte "Fach" passt? 
  - zum Beispiel in der Liste 2017 direkt der erste Eintrag: "Geographie" passt irgendwie nicht zur Fachbezeichnung "Pflanzenphysiologie" oder?
- Welche Spalten können/dürfen mal leer sein
  - Kann ich zum Beispiel davon ausgehen wenn zwar eine ReferentIn eingetragen ist aber keine NetID das die Person dann nicht im System vorhanden ist?
- Soll die Vortragsnummer auch irgendwo auftauchen?

**Comment by sonschul** [comment]
- Eine übergeordnete Instanz mit der Eventreihe fände ich gut. 
- Ich glaube die Bezeichnungen kommen aus der PDF Version des Wissensforums. Das ist nicht die Fach_Bez, sondern die Denomination. Du solltest eigentlich die Spalte Fach (field01) verwenden können. Allerdings ist es tatsächlich nicht korrekt. Es müsste dort field15 stehen... Da muss also noch mal jemand drüber gucken... Du bekommst eine neue Datei. 
- Die Spalte Institut darf leer sein. 
Nur für den Fall, dass keine NetID vergeben wurde (ältere, ehemalige MA), darf auch die NetID Spalte leer sein. 
- Die Vortragsnr muss nirgends auftauchen. Eher für interne Zwecke gedacht.

**Comment by dofeldsc** [comment]
Habe ich so umgesetzt.
Mir ist noch aufgefallen das es zum Teil Aufzählungen in den Texten gibt und das es vllt Sinn macht die Zeilenumbrüche zu bewahren, siehe Beispiel:
ohne Formatierung:
![wissensforum_ohne_formatierung](https://user-images.githubusercontent.com/9248706/65032433-71fdb780-d943-11e9-9d94-5a9d950892fe.png)

mit Formatierung:
![wissensforum_mit_formatierung](https://user-images.githubusercontent.com/9248706/65032441-75913e80-d943-11e9-8ae4-5a2158767de9.png)

mit schöner Formatierung:
![wissensforum_schoene_formatierung](https://user-images.githubusercontent.com/9248706/65038763-fefb3d80-d950-11e9-829b-423b8a29f744.png)

Was gefällt euch besser? (Für mich, wäre mit "white-space: pre-wrap;" in "li" möglich)

Eine andere Frage noch, sind Bilder bzw. ein Bild pro Vortrag geplant? Hatte das jetzt in das Template mit aufgenommen aber ich bin mir gerade nicht sicher.

**Comment by sonschul** [comment]
Mir gefällt die dritte Variante "schöne Formatierung"  auch am besten. 
Es ist zunächst kein Bild vorgesehen, weil schon das Video auf der Seite vorhanden ist. 
Eventuell könnte man aber das Logo zum Wissensforum einbinden (falls es eins gibt...), ist aber aus meiner Sicht kein Muss.

**Comment by dofeldsc** [comment]
Okay, so habe ich es jetzt auch erst einmal eingebaut.
Das Bild nehme ich dann wieder raus

**Comment by dofeldsc** [comment]
Also an sich sind die Daten bereit für den Import. Ich hab sie auch mal ins fis.virtuos.uos.de/vivouos System eingespielt aber so ganz passt das noch nicht.
Die Varianten oben mit der Formatierung funktionieren halt nur wenn der vorliegende Text auch gut formatiert ist...das ist leider nicht immer der Fall. Das führt dann zu sowas:
![mitFormatierung](https://user-images.githubusercontent.com/9248706/66572930-24efb880-eb72-11e9-8f1d-4e51029b8af4.png)

Da kann man auch nicht wirklich was machen außer halt sowas :-/ 
![ohneFormatierung](https://user-images.githubusercontent.com/9248706/66572956-32a53e00-eb72-11e9-8832-c7739097edc7.png)

**Comment by sonschul** [comment]
Bitte noch den header der shortview anpassen: 
![image](https://user-images.githubusercontent.com/40201793/66745651-dc8d0f00-ee7f-11e9-92ea-37b21e47d607.png)

Text zum Kopieren: 
Gemeinsam mit der Universität Osnabrück lädt die Neue Osnabrücker Zeitung jedes Jahr zum Osnabrücker Wissensforum ein. Bürgerinnen und Bürger können vorab Fragen einsenden, die ihnen auf den Nägeln brennen. Die Herausforderung: Jede Wissenschaftlerin und jeder Wissenschaftler hat an dem Abend für seinen Vortrag nur vier Minuten Zeit. Wer überzieht, bekommt die Rote Karte. Mit dem Osnabrücker Wissensforum soll der Dialog zwischen Stadt und Universität gestärkt, der Bedeutung von Wissenschaft für die Zukunftsfähigkeit unserer Gesellschaft gerecht werden und den Blick auf den Wissenschaftsstandort Osnabrück lenken. Nicht zuletzt soll die Vielfalt und Faszination des wissenschaftlichen Arbeitens einer breiteren Öffentlichkeit präsentiert werden.

**Comment by sonschul** [comment]
Es ist noch eine Kleinigkeit in der ShortView für das Wissensforum aufgefallen. 
Bei Personen mit Profil wird unter dem Video die Reihenfolge Nachname, Vorname angezeigt und bei Externen (ohne Profillink) wird Vorname Nachname angezeigt. 

Es wäre schön, wenn wir das vereinheitlichen können auf Nachname, Vorname.

**Comment by dofeldsc** [comment]
Noch offene ToDos:
- [x] Anordnung der Namen ändern 
  - bei schon vorhandenen Personen (Verlinkung NetID) wird "Nachname, Vorname" angezeigt (so wie fast überall)
  - bei nicht im System vorhandenen (nur VCard:Individual angelegt) wird "Vorname Nachname" angezeigt da die Namen so in der Liste angeliefert werden
  - Das einfachste wäre wenn die Daten passend angeliefert würden, da die Unterscheidung zwischen doppelten Vornamen (Schreibweise: "Nachname, Vorname1 Vorname2") und doppelten Nachnamen (Schreibweise "Nachname1 Nachname2, Vorname") nicht möglich ist 
- [x] Wissensforumsbeiträge, bei denen das Video nicht mehr verfügbar ist, sollen nicht mehr angezeigt werden
  - kann man schwer im System lösen
  - Eine Idee wäre beim Import schon zu schauen ob das Video verfügbar ist -> dafür müssten die Daten jedoch regelmäßig "geprüft" und aktualisiert werden
- [x] Änderung der Datenlieferung
  - Spalte "Link zum Video" freilassen wenn kein Video vorhanden ist und nicht mal frei lassen und mal "kein Video vorhanden reinschreiben"
  - Was soll passieren wenn schon bei der Datenlieferung kein Video vorhanden ist? Platzhalter in der Shortview?
  - Ich habe jetzt erst einmal das gestauchte Uni-Logo eingebaut, sollte noch geändert werden
- [x] Default-Logo anpassen (Falls das bleiben soll)
- [X] Fehler in ShortView fixen: Wenn Titel zu lang dann passiert folgendes
![Bildschirmfoto vom 2020-02-11 14-56-15](https://user-images.githubusercontent.com/9248706/74242759-ca609780-4cde-11ea-9316-85c7455eba60.png)

**Comment by dofeldsc** [comment]
Nochmal zur Erinnerung, die Formatierung sieht bei manchen Texten einfach **** aus.
Beispiel: https://fis.uni-osnabrueck.de/vivouos/display/wf1v7

**Comment by dofeldsc** [comment]
Zugehöriges Ticket https://github.com/FISvirtUOS/VIVO/issues/113
