### ISSUE TITLE
Social Media Follow Buttons

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#86]
Um die universitären Social Media Accounts voranzutreiben sollen "Follow-Buttons" in dem Footer der VIVO Seite eingebunden werden. (angelehnt an das Corporate Design der Uni OS) 

Zunächst soll sich auf die folgenden vier Netzwerke beschränkt werden:

Facebook https://fontawesome.com/icons/facebook-square?style=brands
Instagram https://fontawesome.com/icons/instagram?style=brands
Twitter https://fontawesome.com/icons/twitter?style=brands
YouTube: https://fontawesome.com/icons/youtube?style=brands 

![image](https://user-images.githubusercontent.com/40201793/63831617-47859380-c96f-11e9-90dd-7adff7d305b0.png)

**Comment by sonschul** [comment]
Verlinkt werden soll auf die folgenden Accounts:

https://www.facebook.com/uniosnabrueck
https://www.instagram.com/uniosnabrueck/
https://www.youtube.com/user/uniosnabrueck1/
https://twitter.com/UniOsnabrueck

**Comment by sonschul** [comment]
Und noch mal Tweets liked by Uni Osnabrück

`<a class="twitter-timeline" href="https://twitter.com/UniOsnabrueck/likes?ref_src=twsrc%5Etfw">Tweets Liked by @UniOsnabrueck</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

**Comment by dofeldsc** [comment]
Was ist denn hier jetzt genau gewünscht?
Willst du einen Link zu den jeweiligen Seiten mit den Icons oder willst du einen "Follow-Button" so das man beim Klicken direkt dem jeweiligen Profil folgt falls man angemeldet ist (bei der jeweiligen social media Seite) oder halt zur Login-Seite weitergeleitet wird?

Zusätzlich noch:
- Soll sich ein neuer Tab öffnen wenn man das Icon anklickt oder soll sich das im gleichen Tab öffnen?

**Comment by sonschul** [comment]
Neuer Tab mit dem Link zum Profil fände ich am besten.
