### ISSUE TITLE
Vorschlag Template für Embedded Social Media News 

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#87]
Für das Einbetten der Social Media Plattformen würde ich vorschlagen, dass wir eine Seite "Forschungs-News" anlegen, das die verschiedenen Möglichkeiten zum Einbetten der Social Media Plattformen enthält. (Damit keins der anderen Templates geändert werden kann und für Social Media ein eigenes Test-Template angelegt wird.) Den Menü-Punkt könnten wir dann oben im Haupt-Menü für das Testsystem aufnehmen.

Code zum Einbetten folgt...

**Comment by sonschul** [comment]
`<blockquote class="twitter-tweet"><p lang="de" dir="ltr">Wie &quot;real&quot; ist <a href="https://twitter.com/hashtag/VirtualReality?src=hash&amp;ref_src=twsrc%5Etfw">#VirtualReality</a> wirklich?: Studie der <a href="https://twitter.com/hashtag/UOS?src=hash&amp;ref_src=twsrc%5Etfw">#UOS</a> untersucht erzeugte Emotionen durch virtuelle Realität. <a href="https://twitter.com/hashtag/VRBrille?src=hash&amp;ref_src=twsrc%5Etfw">#VRBrille</a> vs. <a href="https://twitter.com/hashtag/2D?src=hash&amp;ref_src=twsrc%5Etfw">#2D</a> vs. echte schwindelnde Höhe. <a href="https://t.co/7PS2yt7rh6">https://t.co/7PS2yt7rh6</a> <a href="https://twitter.com/hashtag/VR?src=hash&amp;ref_src=twsrc%5Etfw">#VR</a> <a href="https://twitter.com/hashtag/UOSforschung?src=hash&amp;ref_src=twsrc%5Etfw">#UOSforschung</a> <a href="https://twitter.com/hashtag/Psychologie?src=hash&amp;ref_src=twsrc%5Etfw">#Psychologie</a> <a href="https://twitter.com/hashtag/H%C3%B6henexposition?src=hash&amp;ref_src=twsrc%5Etfw">#Höhenexposition</a> <a href="https://twitter.com/hashtag/FreiwilligeFeuerwehr?src=hash&amp;ref_src=twsrc%5Etfw">#FreiwilligeFeuerwehr</a> <a href="https://t.co/CXs7oKDMzU">pic.twitter.com/CXs7oKDMzU</a></p>&mdash; Uni Osnabrück (@UniOsnabrueck) <a href="https://twitter.com/UniOsnabrueck/status/1165931865594834946?ref_src=twsrc%5Etfw">August 26, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

**Comment by sonschul** [comment]
Sollte dann so aussehen:
Twitter-News:
![image](https://user-images.githubusercontent.com/40201793/63833249-d942d000-c972-11e9-98f7-e66e852b5113.png)

**Comment by sonschul** [comment]
Und das ganze könnte man auch noch mit den "Tweets liked by UniOS" machen.

Und noch mal Tweets liked by Uni Osnabrück

`<a class="twitter-timeline" href="https://twitter.com/UniOsnabrueck/likes?ref_src=twsrc%5Etfw">Tweets Liked by @UniOsnabrueck</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

**Comment by dofeldsc** [comment]
Also das mit der eigenen Seite für sowas finde ich nicht verkehrt.
Ich hatte das ja schon mal eingebunden (https://fis.virtuos.uni-osnabrueck.de/vivouos/display/n6238) 
Passt da irgendwas nicht oder warum schlägst du jetzt eine andere Art das einzubinden vor?

Wir hatten ja gestern schon mal darüber gesprochen, da hieß es noch das solle auf die Startseite?! Hat sich das dann erledigt? Dann würde ich die Seite einfach mal händisch anlegen

**Comment by dofeldsc** [comment]
Ich habe mal eine Seite angelegt und ein paar Beispiele reingepackt, unter anderem die beiden hier im Ticket genannten. 
https://fis.virtuos.uni-osnabrueck.de/vivouos/socialmediauos

**Comment by sonschul** [comment]
Das finde ich richtig gut! 
In sehr ähnlicher Form ist das sogar bei großen deutschen Universitäten auf den Hauptseiten verlinkt worden. Vielleicht sollten wir das KM auch noch mal zeigen. ;-)

**Comment by dofeldsc** [comment]
Wie ist jetzt der Stand für die Seite? Sollen wir das vllt so machen das ein Pop-Up kommt wenn man das anklickt oder eine extra Seite und dann muss man zustimmen und dann werden die Inhalte erst geladen?

Und wenn wir das so machen dann sollten wir uns mal drüber unterhalten was da genau angezeigt werden soll.

**Comment by sonschul** [comment]
Ich würde vorschlagen, dass wir vor der technischen Umsetzung einen Termin mit dem Anwalt von KM gemacht haben. Damit wir auf der sicheren Seite sind, was die gesetzeskonforme Umsetzung angeht.

**Comment by dofeldsc** [comment]
Das Ticket kann ja erst einmal geschlossen werden da wir außer den Links im Footer und dem Wissensforum keine Social Media Kanäle/Seiten etc. einbinden. 
Bei Bedarf das Ticket einfach wieder öffnen.
