### ISSUE TITLE
Neues Template für Fach mit Page Plugin von Facebook

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#88]
Noch nicht für Montenegro, weil vermutlich in Kürze der Zeit nicht machbar, aber langfristig könnte für die Verbesserung des Templates für "Fach" die Nutzung des Facebook Page Plugins interessant sein. 

Beispiel:
Facebook Page URL: https://www.facebook.com/klipsos/
Für das Fach "Psychologie"
Plugin Code Generator: https://developers.facebook.com/docs/plugins/page-plugin/

![image](https://user-images.githubusercontent.com/40201793/63844876-47928d00-c989-11e9-92b2-cd156733c6a3.png)

**Comment by dofeldsc** [comment]
Das Facebook PlugIn hat sich dann erst einmal erledigt oder?

**Comment by sonschul** [comment]
Hat sich erledigt, wenn es Datenschutzrechtlich große Bedenken gibt. 
Ich werde dazu aber mit KM im Gespräch bleiben... Vielleicht ergibt sich rechtlich mal was Neues.

**Comment by dofeldsc** [comment]
Wenn sich was ergibt kannst du das Ticket dann ja wieder öffnen oder ein neues eröffnen.
