### ISSUE TITLE
Fotos der Professoren für Profilseite

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#9]
Lässt sich in VIVO auch eine URL für ein Profilfoto hinterlegen? 
Über die Oberfläche ist nur ein Upload möglich. 

Dann würde ich Martin bitten nochmal einen Export mit einer Liste der Professoren inkl. Spalte für die URL zum Profilfoto zu schicken.

**Comment by dofeldsc** [comment]
Was meinst du mit URL für ein Profilfoto? Das das Bild da dann automatisch runtergeladen und dann wieder hochgeladen wird oder meinst du das es da eingebettet wird? Beides ist zur Zeit meines Wissens nach nicht enthalten. Man kann bestimmt Fotos importieren bzw. Anlegen und diese wie jede andere Eigenschaft über die Ontologie an die Personen linken. Den Aufwand kann ich so nicht abschätzen

**Comment by sonschul** [comment]
Anders gefragt: 
Kann man je Professor eine Adresse hinterlegen wie (Quelle-Stud.IP): 
https://studip-assets.uni-osnabrueck.de/pictures/user/8d3e22547376cc9a04f4160fb5014ae1_normal.png?d=1418739132

Ich sehe nur die Upload-Seite, um ein Bild auf den Server hochzuladen.
Kann ich gerade nicht anmelden, sonst reiche ich noch mal einen Screenshot nach.

**Comment by dofeldsc** [comment]
Man kann eine Adresse hinterlegen aber diese sollte eine erreichbare sein. Das heißt man sollte die Bilder auf der VM oder einer anderen zur Verfügung stellen, diese in eine Datei eintragen und dann kann ich das mappen und einspielen. Ich denke nicht das das aus Stud.IP heraus möglich ist aber sicher bin ich nicht. Eine abrufbare URL zum Download sollte funktionieren aber besser lokal auf der VM

**Comment by sonschul** [comment]
Hmm... dann ist aber die Frage wie wir das aktuell halten, wenn die Professoren ihre Kontaktdaten (und Foto) nur in Stud.IP pflegen. Alternativ schlage ich vor erstmal ohne Fotos zu arbeiten.

**Comment by dofeldsc** [comment]
Also ich habe mich mal schlau gemacht. Stud.IP könnte mir eine Liste von Benutzerkennung + URLs zu den Profilbildern liefern aber
1. Nur für die Leute, welche auch zugestimmt haben ihre Bilder auch für andere Seiten zur Verfügung zu stellen (Option in Stud.IP beim Upload)
2. Mit dem Datenschutzbeauftragten klären ob das FIS schon als uniweiter Dienst gilt und andere rechtliche Bestimmungen...
3. Das könnte man einmalig machen, das updaten sieht da schon schwerer aus. Dazu müsste man sich Gedanken machen und wahrscheinlich auch in Stud.IP etwas anpassen und einer entsprechenden Service bauen

**Comment by dofeldsc** [comment]
Achja das könnte sich aber bald alles erledigt haben...Auch das mit den IDs. ES gab anfangs ein Treffen mit der Personendaten AG in der das Rechenzentrum das Konzept für das IDM vorgestellt hat. Sobald das fertig ist hat man alles was wir wollen. Die sollen alle Daten (Bilder, Kontaktdaten, IDs, etc) zusammenfassen und für andere Systeme zur Verfügung stellen. Da könntet ihr mal anfragen wie der Stand da ist

**Comment by sonschul** [comment]
Ich frag gerne nach einem aktuellen Stand, aber ich hab wenig Hoffnung, dass es da schon etwas Neues gibt. :-/

**Comment by sonschul** [comment]
Wenn das IDM zeitnah kommt, könnte man auch trotzdem die Schiene fahren, dass man einmal initial lädt und danach die Schnittstelle zum IDM abwartet.

**Comment by sonschul** [comment]
Fotos der Professoren werden als Datei zur Verfügung gestellt. 
IDM ist vorläufig auf Eis gelegt...
