### ISSUE TITLE
Überarbeitung des Templates ShortView Projects

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#90]
Sammelticket für die Überarbeitung der ShortView Projects 

![image](https://user-images.githubusercontent.com/40201793/67479375-351d9280-f65e-11e9-8d4a-23189483358a.png)

Projektstatus: soll nur nach laufend / abgeschlossen filtern können
Mittelgeber: soll anhand einer vorgegebenen Liste aus allen "verwendeten" Mittelgeber filtern
Fachbereich: soll anhand einer vorgegebenen Liste aus allen genannten Fachbereiche filtern
(Fach : eventuell ebenso einen Filter für das zugeordnete Fach, um Bspw. Biologie / Chemie trennen zu können.) 

Der vorangestellte Pfeil vor "Drittmittelprojekte" soll entfernt werden, um nicht den Eindruck zu erwecken, dass dadurch gefiltert werden könne. Idealerweise aktualisiert sich die Zahl der Projekte (in Klammern) auf die Anzahl der gefilterten Objekte.

**Comment by dofeldsc** [comment]
So die Projektübersicht mit Filtern ist soweit "fertig" und ist auf dem [Testsystem](https://fis.virtuos.uos.de/vivouos) verfügbar. 
Testet das mal bitte und guckt besonders ob sich das so verhält wie ihr euch das wünscht. Feedback gerne einfach hier im Ticket.

**Comment by sonschul** [comment]
Können wir hinter dem ersten Eintrag noch (alle) ergänzen? 
Oder alternativ so wie auf der Seite der Hochschule "Alle" als eigenen Filter? 

Den MG Filter würde ich lieber rausnehmen. Den zweiten Filter auf Mittelgeber braucht man m.M.n. nicht. 
Ist es möglich die Filter kaskadierend einzubauen?

**Comment by kaschnie** [comment]
Ich führe hier auch einfach mal auf, was mir spontan beim ersten Drüberschauen aufgefallen ist:

- Den zweiten Filter auf den Mittelgeber würde ich auch rausnehmen und die Filterbox auf Mittelgeber noch rechts neben die Filterbox Fachbereich verschieben?!

- „Alle“ als Filtermöglichkeit im DropDown-Menü – wie bei der Hochschule – könnte man wirklich mit aufnehmen, damit das als Filterauswahl deutlicher wird
![grafik](https://user-images.githubusercontent.com/44695704/72051696-09f12980-32c4-11ea-9f99-fbdb955df120.png)

- Der rote Pfeil vor Drittmittelprojekte erwirkt den Anschein als könne man beim Draufklicken auch filtern oder das sich ebenfalls ein DropDown-Menü öffnet. Vielleicht könnte man den Pfeil rausnehmen. Wenn man übrigens etwas gefiltert hat und dann auf den Drittmittelprojekte Button klickt, werden alle Filter automatisch zurückgesetzt. Vielleicht könnte man das ausstellen?

- Die Hochschule hat in die alphabetische Sortierung eine "#" aufgenommen für Projekte, deren Projekttitel mit Zeichen oder Zahlen beginnen. Das wäre bei uns meiner Meinung nach auch ganz sinnvoll, weil diese Projekte bei uns momentan nur in der Gesamtübersicht angezeigt werden.
![grafik](https://user-images.githubusercontent.com/44695704/72051883-59375a00-32c4-11ea-9e2a-1fdcc0173dc9.png)

**Comment by dofeldsc** [comment]
- Das mit Alle hinter der ersten Auswahl kann man mit aufnehmen, einen extra Punkt würde ich nicht machen weil sonst hat man die Auswahl "Keinen Filter" doppelt. Oder man schreibt das Label, also z.B. Mittelgeber-Filter: , neben die Auswahl und nennt den ersten Punkt Alle- Was euch lieber ist.
- Das mit dem roten Pfeil verstehe ich aber das sollte man wenn dann auf allen Übersichtsseiten entfernen und dann wird da nicht mehr deutlich das die Felder anklickbar sind. Was könnte man denn sonst nehmen um das deutlich zu machen?
- Den "Drittmittelbutton" würde ich nicht entfernen weil die Funktionalität auf allen Übersichtsseiten so ist und wenn sich dann nur eine Seite anders verhält verwirrt das die meisten Nutzer. Man könnte es so machen das anstatt die Filter zurückgesetzt werden und die "normale" Auswahl geladen wird das man wieder auf die erste Seite der aktuellen Filter springt. Was sagt ihr dazu?
- das # in die Sortierung mit aufnehmen finde ich gut, muss ich mal schauen wie sich das da umsetzen lässt.
- kaskadierende Filter sind an sich möglich aber ich fürchte an der Stelle nicht praktikabel. Da die Informationen nicht im Suchindex vorhanden sind muss man jedes mal eine SPARQL-Abfrage über alle Drittmittelprojekte machen. Das wird wahrscheinlich zu lange dauern um das gut in die Suchauswahl zu integrieren.

Wie kommt es das ihr plötzlich nicht mehr nach mehreren Mittelgebern filtern wollt? Das habe ich doch extra auf euren/deinen Wunsch eingebaut...

**Comment by kaschnie** [comment]
Vielleicht können wir bei unserer Rücksprache am Donnerstag über die Punkte sprechen und gemeinsam überlegen?!

Die Filtermöglichkeit nach mehreren Mittelgebern hatte ich mir so vorgestellt, wie wir das öfter in unseren Cognos-Reports einbauen ;-) ... Hier mal ein Beispiel: 
![grafik](https://user-images.githubusercontent.com/44695704/72262063-6df25580-3616-11ea-8131-a81ab58c88a1.png)

**Comment by dofeldsc** [comment]
Wie in unserem heutigen Treffen besprochen wird folgendes umgesetzt:
- [X] die Filter Mittelgeber werden mit neuer "Multiple Search Selection" umgesetzt (Beispiel https://semantic-ui.com/modules/dropdown.html#multiple-selection)
- [x] Sonderzeichen wie # werden zur Auswahl (alpha) hinzugefügt
  - führt zu erheblichen Problemen, an sich für die Filtervariante kein Problem (ist auch schon eingebaut) aber für die normale im System integrierte nicht...
- [X] Text ändern wenn keine Treffer gefunden wurden
- [X] Kaskadierende Filter mal ausprobieren (die Abfrage könnte zu zeitintensiv sein)
  - vllt in einer späteren Version, so jetzt erst einmal zu aufwendig und zu zeitintensiv für das System

**Comment by dofeldsc** [comment]
Hier nochmal kurz die Zusammenfassung der heute besprochenen Anpassungen:
- [x] Extra Anzeige der gewählten Filter ausbauen
- [X] Hintergrundfarbe bei der Auswahl auf Rot (Coporate Design) ändern
- [X] Bei "Reset Filter" auch Mittelgeber zurücksetzen
- [X] Bugfix bei der Suche
- [X] Speichern der Filter ausbauen
  - Die Auswahl bleibt gespeichert aber nicht die Filter, das ist wohl Standard (vllt nochmal drüber reden ob das so bleiben kann)
- [x] Filter für Fächer hinzufügen
- [x] Sonbderzeichen alpha auch wenn keine Filter gesetzt sind (wird angezeigt, funktioniert noch nicht)
- [x] Wenn keine Filter ausgewählt sind, reset Filter nicht mehr anzeigen (leere Suche ist okay)


Für V2 (dann in neues Ticket übertragen)
- [ ] Kaskadierenden Filter
  - Die nicht mehr sinnvollen Auswahlmöglichkeiten ausblenden (z.B. wenn FB01 ausgewählt ist das Fach Informatik ausblenden
- [ ] i18n Support

**Notiz:** Da die Verbundprojekte generell keine Laufzeit haben werden diese trotzdem auch bei laufenden angezeigt (bleibt vorerst so). EIne Idee von uns war beim Import zu schauen ob alle Terilprojekte abgeschlossen sind bzw. längste Laufzeit auch beim Verbundprojekt zu setzen.

**Comment by sonschul** [comment]
Als Erweiterung zur bisherigen Filtermöglichkeit sollen die Fächer kaskadierend gefiltert werden. 
Die nicht zum Fachbereich zugehörigen Fächer werden nach Auswahl eines FB ausgegraut oder ausgeblendet.

**Comment by sonschul** [comment]
- [x] "Filter anwenden" und "Filter zurücksetzen" statt als klassischen Button nur als Text einbinden.  
ähnlich wie hier: 
![image](https://user-images.githubusercontent.com/40201793/89886178-7d497980-dbcc-11ea-955c-3f1276f49dfa.png)

- [x] Leerzeichen vor Mittelgeber, damit das M nicht direkt am Rand steht.
![image](https://user-images.githubusercontent.com/40201793/89886198-86d2e180-dbcc-11ea-881d-419079dda950.png)

**Comment by dofeldsc** [comment]
Die erste Version ist jetzt online und alle offenen Punkte wurden in das Nachfolgeticket https://github.com/FISvirtUOS/VIVO/issues/103 übernommen.
