### ISSUE TITLE
Professoren-Profilfotos von KM einbinden

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#91]
Die von KM aufgearbeiteten Bildern mit Copyright-Hinweis und der von Urna überarbeiteten Bezeichnung der Bild-Datei (alle nun mit NetID) liegen in der Academic Cloud unter:

https://sync.academiccloud.de/index.php/apps/files?dir=/FIS/VIVO%20Daten/person/profilbilder

Bei Gelegenheit bitte testen, ob die Profilbilder für das VIVO - System geeignet sind.

**Comment by dofeldsc** [comment]
Sind im Testsystem hinterlegt

**Comment by dofeldsc** [comment]
Nach Absprache sollen in der Shortview (Listenansicht) der Personen für Personen ohne Foto das Platzhalterfoto angezeigt werden. Das lässt sich wahrscheinlich mit eine kleinen Änderungen im Template realisieren.

**Comment by sonschul** [comment]
Aus meiner Sicht ist bei den Profilfotos alles in Ordnung und kann so ins Produktivsystem übernommen werden. Die Qualität einiger Bilder ist zwar fragwürdig, aber darüber lässt sich wohl streiten.
