### ISSUE TITLE
Promotionen anbinden mit repOSitorium

### ISSUE THREAD

**Issue by sonschul** [FISvirtUOS/VIVO#95]
https://repositorium.ub.uni-osnabrueck.de/
Open Access - repOSitorium für abgeschlossene Promotionen in VIVO integrieren. 

Darstellung testen

**Comment by dofeldsc** [comment]
In diesem Ticket erledigt https://github.com/FISvirtUOS/uos_fis_doku/issues/58 
Den Rest (andere Publikationen) beziehen wir dann aus der Hochschulbibliographie
